### ISSUE TITLE
Need synchronization method

### ISSUE THREAD

**Issue by zhenlinyang** [Tyrrrz/CliWrap#106]
Hi, I hope that the synchronization method can be retained, because in some application scenarios, only a piece of logic needs to be executed stably without considering performance.

**Comment by Tyrrrz** [comment]
Do you mean `Execute()` instead of `ExecuteAsync()`? You can just call `ExecuteAsync().GetAwaiter().GetResult()` if you want to run it synchronously.

**Comment by zhenlinyang** [comment]
Yes, I need a synchronization method `Execute()`, `ExecuteAsync().GetAwaiter().GetResult()` can be used. Thank you.
