### ISSUE TITLE
Support for process jobs on Windows

### ISSUE THREAD

**Issue by wasabii** [Tyrrrz/CliWrap#111]
It would be nice if CliWrap provided easy functionality for ensuring the child process was terminated on Windows when the parent process was terminated. This requires some P/Invoke stuff.

```

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
        static extern IntPtr CreateJobObject(IntPtr lpJobAttributes, string name);

        [DllImport("kernel32.dll")]
        static extern bool SetInformationJobObject(IntPtr job, JobObjectInfoType infoType,
            IntPtr lpJobObjectInfo, uint cbJobObjectInfoLength);

        [DllImport("kernel32.dll", SetLastError = true)]
        static extern bool AssignProcessToJobObject(IntPtr job, IntPtr process);
```

But, you can use it to attach the child to the parent.

Perhaps a CliWrap.Windows extension package?

**Comment by wasabii** [comment]
@Tyrrrz Is there any ability to alter the execution process through extension methods? If so, I'd add this myself.

I was thinking something about a Command having a delegate list accepting the ProcessStartInfo, or something. Or a set of delegates for lifecycle stuff. Like, on starting, started, ending, etc, that you could append to.

**Comment by Tyrrrz** [comment]
Nope. Process stuff is not exposed. You can get process ID though, which sound like it should be enough for what you need.

**Comment by wasabii** [comment]
Yeah. That's what I'm doing. But I can't make it an extension method, since there's no hooks for it.

For instance, I'd like to be able to write Cli.Wrap("foo.exe").WithWin32Job() or some such. But, I'd have to have WithWin32Job() be able to setup a callback to run at some point inside Cli.Wrap.

Being unable to do this means you can't just await ExecuteAsync, for instance: `await cmd.ExecuteAsync()`...... no place to get the PID and do stuff. Instead, you have to NOT await, use the PID, then await. Not a clean experience.

**Comment by Tyrrrz** [comment]
You can make an extension method like this:

```csharp
public static CommandTask<CommandResult> ExecuteAsync(this Command cmd, Action<CommandTask<CommandResult>> handleTask)
{
    var task = cmd.ExecuteAsync();
    handleTask(task);
    return task;
}

await Cli.Wrap("foo").ExecuteAsync(t => DoSomethingWithProcess(t.ProcessId));
```

**Comment by matthewsheeran** [comment]
How do you get that Process Id (or Process which is what I think I did: make it public from private) itself?
I took a local copy of the code to fork it to get this a long time ago.
BTW: I am killing sub-processes myself - which finally solved my issue above of sub processes left running - forget the P/Invoke it's not required nnor is saving any Child Processes and associating them as a Job.
It's a tiny bit clunky but very effective with low line count which is almost always my metric.

Answer the above (or else make the Cli Process public as I did) and I'll try your new code base and share my code.
But if Process is still inaccessible to the caller I'll probably stick with what I have instead along with lines like:

```
        public void Kill()
        {
            if (this.Cli?.Process?.HasExited == false)
            {
                try
                {
                    /// Kill Cli Process.
                    int processId = this.Cli?.Process?.Id ?? 0; // Either Cli Process Id or else this one.
                    this.Cli?.Process?.Kill();
                    /// Kill All Children of either Cli Process or else this one.
                    this.KillChildren(processId);
                }
                catch { }
            }
        }
```
Its the KillChildren(pid) which I can reveal that is just 16 LoC and works like a very reliable charm..

Kindest Regards
Matthew

**Comment by powercode** [comment]
Jobs are a bit tricky to support since the Process class does not allow the creation of a suspended process.

Otherwise, it is about creating a job object, creating a suspended process, and adding the process to the job.

But since interop code is needed to create the process object, it is a bit tricky to get a ProcessClass from it with redirected output stream set.

**Comment by Tyrrrz** [comment]
Yeah, I'm going to just suggest getting the process ID from `CommandTask` and adding the process to the job manually. I don't think it makes much sense to have native support for this in CliWrap since, like @powercode said, we can't add a process to a job before it's started anyway.
