### ISSUE TITLE
Doesn't work on Ubuntu

### ISSUE THREAD

**Issue by haggerty-william** [Tyrrrz/CliWrap#12]
System.ComponentModel.Win32Exception (0x80004005): Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.
   at System.Diagnostics.Process.GetStat()
   at System.Diagnostics.Process.get_StartTimeCore()
   at System.Diagnostics.Process.get_StartTime()
   at CliWrap.Cli.Execute(ExecutionInput input, CancellationToken cancellationToken, IBufferHandler bufferHandler)

I tried executing my app with sudo and without, gave file execute permission, I don't really know if it's my problem or the library, although I had it working while using the Process class.

**Comment by Tyrrrz** [comment]
No it wasn't tested, in fact you were probably the first person to try it. 😄 
Looks like for some reason it can't get process start time to generate `ExecutionOutput`.

**Comment by Tyrrrz** [comment]
Interesting. Googling the problem shows that `StartTime` property is not accessible after the process exited, although it seems it's not enforced on Windows.

**Comment by Tyrrrz** [comment]
Fix version is built and deployed, you should be able to update your nuget package soon https://ci.appveyor.com/project/Tyrrrz/cliwrap/build/52
