### ISSUE TITLE
Add byte[] pipe operator support for pipe source

### ISSUE THREAD

**Issue by silkfire** [Tyrrrz/CliWrap#125]
### Details

Would it be possible to add an additional pipe operator overload that supports byte arrays?

Example:

`byteArray | Cli.Wrap(...)`

which internally is converted to:

`PipeSource.FromBytes(byteArray) | Cli.Wrap(...)`

**Comment by Tyrrrz** [comment]
Sure. I'm surprised it wasn't already there. PRs welcome for this.
