### ISSUE TITLE
Drop support for targets below net5.0

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliWrap#131]
### Details

The plan is to drop support for targets below net5.0 in the next major bump (#130).
Main reasoning is that targeting older frameworks is holding this library back from making use of some of newer features that cannot be reasonably pollyfilled, like `await using`. Additionally, it will simplify the code quite a bit.

This issue is open for discussion if you have any comments or questions.

**Comment by SlowLogicBoy** [comment]
This kind of affects me since some of our products run on LTS releases and we are currently on netcoreapp3.1.

**Comment by Tyrrrz** [comment]
> This kind of affects me since some of our products run on LTS releases and we are currently on netcoreapp3.1.

Are you planning to upgrade to .NET 6 anytime soon (which is also LTS)?

**Comment by SlowLogicBoy** [comment]
We are planning to when our internal libraries that we depend on will support it (mainly asp.net core changes need to be done).

I don't think dropping 3.1 support will be a huge deal for us, only if some breaking bugs come up, but since our use-case is really simple it might not be a problem, but we are planning to start using pipelines, because that will increase our performance instead of opening and closing terminal with each request.

**Comment by chucker** [comment]
This affects me while I'm still on Xamarin Forms (which is Mono / .NET Standard 2.1). MAUI (which uses .NET 6) is still in preview for now.

If critical bugs should come up for 3.x, will you do maintenance releases for that for a while longer?

**Comment by Tyrrrz** [comment]
> This affects me while I'm still on Xamarin Forms (which is Mono / .NET Standard 2.1). MAUI (which uses .NET 6) is still in preview for now.

Thanks for letting me know. Is there any ETA for when MAUI is going to be available in a stable release?

> If critical bugs should come up for 3.x, will you do maintenance releases for that for a while longer?

I would say yes, but at that point it's far easier to just not drop support for old frameworks altogether, I think.

Right now I'm still trying to measure the impact of this change, but it's hard to effectively poll people. :/

**Comment by chucker** [comment]
> Is there any ETA for when MAUI is going to be available in a stable release?

They're aiming for a release in Q2, but I think it'll be a while until people have managed to migrate. It's kind of a big change.

> it's hard to effectively poll people

Indeed. :)

**Comment by Tyrrrz** [comment]
FYI, decided to postpone this indefinitely, but whenever 4.x comes, it will most likely include this breaking change.

**Comment by taori** [comment]
What about adding Microsoft.Bcl.AsyncInterfaces for <net5.0 and doing a crosscompile? It's some extra work but that way there would be nothing holding this back? (Willing to contribute)

**Comment by Tyrrrz** [comment]
> What about adding Microsoft.Bcl.AsyncInterfaces for <net5.0 and doing a crosscompile? It's some extra work but that way there would be nothing holding this back? (Willing to contribute)

It's already what we do, but then we can't use `await using var` because some of the frameworks that we target don't have `IAsyncDisposable` on BCL types (e.g. `Stream`). There is a workaround in place for that now.

**Comment by Tyrrrz** [comment]
Just FYI, this issue is on indefinite hold. I'd consider dropping older frameworks if there are enough other changes that would otherwise warrant a new major version. So far, that doesn't seem likely to happen, as most features from the v4 branch were successfully backported to v3 without too much hassle. I'm going to close this issue for now, until (if) v4 becomes a prospect again.

**Comment by taori** [comment]
Glad to see lower targets are not dropped for no reason. I am seeing this library used more frequently even in some old projects because of the current integration
