### ISSUE TITLE
Non-Fluent usage leads to ignoring WithArguments

### ISSUE THREAD

**Issue by sandreas** [Tyrrrz/CliWrap#138]
### Version

3.4.0

### Details

While the following works like expected sleeping 5 seconds:

```c#
    var command = Cli.Wrap("sleep").WithArguments(new[]
    {
        "5"
    });
    await command.ExecuteBufferedAsync();
```

the following does not work but passes without sleeping 5 seconds (seems that arguments are ignored):

```c#
    var command = Cli.Wrap("sleep");
    
    command.WithArguments(new[]
    {
        "5"
    });
    await command.ExecuteBufferedAsync();
```

Am I doing something wrong? I did not find anything in the docs, that this is not allowed. I needed this for conditional arguments:

```c#
    var someSetting = 5;
    var command = Cli.Wrap("some-command");
    if(someSettings < 5) {
      command.WithArguments(new[]
      {
          "5"
      });
    }
    await command.ExecuteBufferedAsync();
```

### Steps to reproduce

- Install `3.4.0`
- Run the short code snippet from Details section:

```c#
    var command = Cli.Wrap("sleep");
        command.WithArguments(new[]
    {
        "5"
    });
    await command.ExecuteBufferedAsync();
```

**Comment by Tyrrrz** [comment]
The `With...` methods are pure, they return immutable objects: 
![image](https://user-images.githubusercontent.com/1935960/151685510-ad919af5-6b00-4c82-a319-f7d5850584c8.png)

**Comment by sandreas** [comment]
> The With... methods are pure, they return immutable objects:

Thank you for clearing this up and sorry for not reading the docs carefully :-/ I greatly appreciate `CliWrap` and think its an awesome library :-)

**Comment by Tyrrrz** [comment]
> > The With... methods are pure, they return immutable objects:
> 
> Thank you for clearing this up and sorry for not reading the docs carefully :-/ I greatly appreciate `CliWrap` and think its an awesome library :-)

You're welcome :)
