### ISSUE TITLE
Wrong process ID if target executable doesn't exist

### ISSUE THREAD

**Issue by alex6dj** [Tyrrrz/CliWrap#139]
### Version

3.3.3

### Details

When I try tu run an executable using this library, and the executable dont exist, it reports process id as zero. The problem is that the zero process id is valid and it represent the `System Idle Process,` it is not really a process but can cause a `Win32Exception` if you try to change his id process priority.

### Steps to reproduce

This is part of my code

- Install library

- Execute a command but with a wrong executable path (Windows).

```csharp
string ffmpegPath = "...";

var cmd = Cli.Wrap(ffmpegPath)
                .WithValidation(CommandResultValidation.None)
                .WithArguments(arguments);

var observable = cmd.Observe(cancellationToken).Publish();

var changePriority = observable.Select(x => x as StartedCommandEvent)
                .Where(x => x != null)
                .Take(1)
                .Select(x => x.ProcessId)
                //.Where(x => x > 0)   // This filters the process id only accepting values above zero
                .Subscribe(SetPriorityByProcessId); // Proccess id == 0  then Win32Exception

observable.Connect()

void SetPriorityByProcessId(int processId)
{
    var process = Process.GetProcessById(processId);
    process.PriorityClass = ProcessPriorityClass.BelowNormal;
}
```

**Comment by alex6dj** [comment]
I think we should avoid the use of process id zero or at least inform the behaviour.

**Comment by Tyrrrz** [comment]
If the target file path doesn't exist, it should throw an exception before it even produces `StartedCommandEvent`. Are you sure that's what's happening?

**Comment by alex6dj** [comment]
Yes, I am sure this is what is happening in my case. I am going to try to create a small project to replicate the error.

**Comment by alex6dj** [comment]
Project done.
[CliWrapWrongIdExample](https://github.com/alex6dj/CliWrapWrongIdExample)

**Comment by alex6dj** [comment]
This use latest version (3.4) and same behaviour.

**Comment by Tyrrrz** [comment]
Thanks I'll take a look

**Comment by Tyrrrz** [comment]
Thank you for the report, fixed
