### ISSUE TITLE
Consider maintaining changelog

### ISSUE THREAD

**Issue by Nekromancer** [Tyrrrz/CliWrap#14]
Hey,
Great library you have here. I would suggest you to keep some kind of changelog for users, so we can keep up with what is new. Probably simple CHANGELOG.md would be good enough

**Comment by Tyrrrz** [comment]
Hi. Why not commit history? :P

**Comment by Nekromancer** [comment]
Well, when i have to follow the changes of multiple libraries (which happens all the time) i would rather lookup short CHANGELOG (which, for example, states that braking change has been made and links to migration guide) then go through long commit history and track all code changes. It's cumbersome given limited time and 10 libraries to follow up :)

**Comment by pipe01** [comment]
I would agree that having a short changelog for each version would be more
convenient.

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/CliWrap/blob/master/Changelog.md
