### ISSUE TITLE
Can not redirect standard output from bash `read` command prompt

### ISSUE THREAD

**Issue by my522cn** [Tyrrrz/CliWrap#140]
### Version

3.4.1

### Details

The 'read' shell script can not be redirect to StandardOutput.

Here's the C# code:
```C#
var cmd = Console.OpenStandardInput() | Cli.Wrap(path).WithStandardOutputPipe(PipeTarget.ToStream(Console.OpenStandardOutput()));
await cmd.ExecuteAsync();
```

Here's the shell code
```Shell
#!/bin/bash
echo ""
echo ""
echo ""
echo ""
echo ""
echo "I'm #1"
read -t 3 -p "Ready for test press any key or wait for 3 s" k
echo "I'm #2"
read -t 3 -p "Ready for test press any key or wait for 3 s" k
echo "I'm #3"
read -t 3 -p "Ready for test press any key or wait for 3 s" k
echo "I'm #4"
read -t 3 -p "Ready for test press any key or wait for 3 s" k
RESULTFILE=./test.result
echo "PASS">${RESULTFILE}
ls
```

![Snipaste_2022-02-23_17-24-56](https://user-images.githubusercontent.com/11346219/155291727-06fbafc7-7561-4caa-9d3d-f0130daef847.png)

"Ready for test press any key or wait for 3 s" was not printed

### Steps to reproduce

As details above.

**Comment by Tyrrrz** [comment]
Can you check if the same thing works using `Process`?

```csharp
using var process = new Process
{
    StartInfo =
    {
        FileName = path,
        RedirectStandardOutput = true
    }
};

process.Start();
var output = process.StandardOutput.ReadToEnd();
```

**Comment by my522cn** [comment]
> Can you check if the same thing works using `Process`?
> 
> ```cs
> using var process = new Process
> {
>     StartInfo =
>     {
>         FileName = path,
>         RedirectStandardOutput = true
>     }
> };
> 
> process.Start();
> var output = process.StandardOutput.ReadToEnd();
> ```

it works using Process:
but without \n
![Snipaste_2022-02-24_08-40-14](https://user-images.githubusercontent.com/11346219/155434980-5022fd1c-8454-4f39-96e0-4c0ab967b8aa.png)

**Comment by Tyrrrz** [comment]
I'd appreciate it if you can figure out where the bug is in CliWrap. I'm currently preoccupied with a war looming on the horizon. 🙁

**Comment by my522cn** [comment]
It's incredibly challenging for me. I will PR if I figure the bug out.

**Comment by Tyrrrz** [comment]
I did this in command line:

```bash
/bin/bash -c "echo test1; read -r -p test2; echo test3" > foo.txt
```

The output file contained only:

```txt
test1
test3
```

So it might be that's just how `read` works when stdout is redirected?

**Comment by Tyrrrz** [comment]
Tested using `System.Diagnostics.Process` with the below code, the result is the same.

```csharp
    using var process = new Process
    {
      StartInfo =
      {
          FileName = "/bin/bash",
          Arguments = "-c \"echo test1; read -r -p test2; echo test3\"",
          RedirectStandardOutput = true
      }
    };

    process.Start();
    var output = process.StandardOutput.ReadToEnd();
```

Closing as it doesn't seem to be a problem with CliWrap.
