### ISSUE TITLE
NO POLITICS, ONLY CODE PLEASE!

### ISSUE THREAD

**Issue by yukuyoulei** [Tyrrrz/CliWrap#155]
### Details

NO POLITICS, ONLY CODE PLEASE!

**Comment by Tyrrrz** [comment]
Let me think about it for a second.

**Comment by Tyrrrz** [comment]
Nah, I'll keep it this way.

**Comment by alina-yur** [comment]
There is a very clear line between politics and war. Politics is how much taxes you are paying and what you expect in return, what are the social policies in your country, what you as a society think about healthcare, migration, ecology. When civilians are being killed, raped, and tortured, it's not politics.

**Comment by tardezyx** [comment]
Humans have political views, software doesn't. It's like "you are only allowed to use this hammer if you have proven your Gesinnung" which should alert every reasonable mind as this is a authoritarian political standpoint itself.
