### ISSUE TITLE
Run as administrator or other user

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliWrap#16]
Implement "runas"

**Comment by Tyrrrz** [comment]
Decided this is out of scope until an actual user need appears.

**Comment by HamedFathi** [comment]
I think you can support `Verb` for this purpose. It is useful when we want to integrate your library into our CI/CD systems. please add this :)

**Comment by Tyrrrz** [comment]
It's actually more difficult than this, because in order to use `runas` verb you have to run the process with shell execute, which means you won't be able to read its stdout/stderr anymore. A process ran as non-administrator cannot gain access to a process ran as administrator.

In order to do this properly, you need to launch the original process as administrator then all child processes will also have elevated access.

**Comment by garyng** [comment]
https://github.com/gerardog/gsudo is a prior art which we probably can refer to.
