### ISSUE TITLE
Older net-framework versions support

### ISSUE THREAD

**Issue by Nucs** [Tyrrrz/CliWrap#18]
Hey, any chance to release support for old netframework versions for tools like installers that need to aim for atleast net3.5 that comes by default with windows 7?

It doesn't have to have async methods, so you can reduce the overhead with BCL libs.

Regards, Eli.

**Comment by Tyrrrz** [comment]
Hi.
I have no intention of supporting legacy frameworks. Net35 lacks more than just the TPL for async so it would it probably be easier to make a new library than to make this one compatible.

**Comment by Nucs** [comment]
I do agree regarding NET35, even atleast NET40 would be better.
It did not take me more than 5 minutes of work..

1. changed target framework.
2. removed the only single asnyc method (you can just hide it with define NET35
3. changes any `.Configureawait(false)` to `.Wait()`.
4. compile

Thank you anyways

**Comment by Tyrrrz** [comment]
What about cancellation token?
