### ISSUE TITLE
Ripgrep returns exit code 1 with no stdout or stderr, can't work out why

### ISSUE THREAD

**Issue by dracan** [Tyrrrz/CliWrap#190]
### Version

3.6.0

### Details

I'm trying to use this to run Ripgrep, but it always returned errorcode 1 with nothing in the stdout. Not sure why.

### Steps to reproduce

Here's an example...

![image](https://user-images.githubusercontent.com/567988/212709706-5f0ad287-5c02-4339-a257-7ea6a75e44da.png)

On the left, I'm trying to run `rg rabbit`, and it fails with no reason. On the right, if I use `rg --help`, this does work.

Running this natively on the command line...

![image](https://user-images.githubusercontent.com/567988/212709847-217fba3c-bcdc-4a44-a287-388f68c12c11.png)

So I think that's proving that `rg rabbit` is writing to the stdout stream. But I can't see why it would fail when running the same command through CliWrap.

Code from screenshot is here:

```csharp
var result = await Cli.Wrap("rg")
    .WithArguments(new[] {
        "rabbit",
    }, false)
    .WithWorkingDirectory(@"C:\Dump\GrepTest\")
    .WithValidation(CommandResultValidation.None)
    .ExecuteBufferedAsync();

result.Dump()
```

Ps. just want to also say thank you for the awesome project! I can't believe it's so difficult to do this kind of stuff in .NET natively! Very grateful of you spending the time to make this easier! 🙏🏼

**Comment by dracan** [comment]
HI @Tyrrrz. Thank you so much for looking into that, and for your very detailed reply! Especially as it involved a different tool that you're not involved in 🙏🏼
Good to know for future reference that CliWrap is _always_ redirecting input streams though - as I guess Ripgrep probably isn't going to be the only tool that does similar (I know of a few that act differently when being piped to).
Thanks again for the awesome library 🙂

**Comment by Tyrrrz** [comment]
> HI @Tyrrrz. Thank you so much for looking into that, and for your very detailed reply! Especially as it involved a different tool that you're not involved in 🙏🏼 Good to know for future reference that CliWrap is _always_ redirecting input streams though - as I guess Ripgrep probably isn't going to be the only tool that does similar (I know of a few that act differently when being piped to). Thanks again for the awesome library 🙂

You're welcome!
