### ISSUE TITLE
Add `WithArguments` overload (or new method) that allows appending arguments to an existing command

### ISSUE THREAD

**Issue by MindSwipe** [Tyrrrz/CliWrap#209]
### Details

Currently calling `WithArguments` returns a new command where any potential arguments already added are cleared, for example when doing:

```csharp
var command = Cli.Wrap("ping").WithArguments(new [] { "-t" });

if (_options.UseIPV6)
    command = command.WithArguments(new [] { "-6" });
```

Results in the command

    ping -6

---

The current workaround is to do something like this:

```csharp
var arguments = new List<string> { "-t" };

if (_options.UseIPV6)
    arguments.Add("-6");

var command = Cli.Wrap("ping").WithArguments(arguments);
```

which is a little cumbersome.

**Comment by Tyrrrz** [comment]
Why not do this?

```csharp
var command = Cli.Wrap("ping").WithArguments(args =>
{
	args.Add("-t");
	if (_options.UseIPV6)
		args.Add("-6");
});
```

The builder overload was made specifically for these type of scenarios.

**Comment by Tyrrrz** [comment]
Going to close this issue, since the above suggestion should satisfy the highlighted use case. Let me know if there's another scenario where you'd need to extend arguments of an existing command.
