### ISSUE TITLE
Allow input midway through a script's execution

### ISSUE THREAD

**Issue by thomhurst** [Tyrrrz/CliWrap#220]
### Details

From what I can tell, input is piped to a process immediately when the process has begun.

However, some scripts might ask for prompts.

But if I have an input stream pipe, trying to write to it at the time I have a prompt does nothing.

### Checklist

- [X] I have looked through existing issues to make sure that this feature has not been requested before
- [X] I have provided a descriptive title for this issue
- [X] I am aware that even valid feature requests may be rejected if they do not align with the project's goals
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
This is already possible using the approach described in https://github.com/Tyrrrz/CliWrap/discussions/194

**Comment by thomhurst** [comment]
Hmm it's seems a powershell Read-Host command doesn't seem to trigger any command events?

**Comment by Tyrrrz** [comment]
I don't know how `Read-Host` works specifically, but it might be that the prompt isn't actually written to stdout.

**Comment by thomhurst** [comment]
Yeah I think you're right. I don't really think there's a workaround then for what I'm trying

**Comment by Tyrrrz** [comment]
Going to close this now since the issue doesn't seem specific to CliWrap
