### ISSUE TITLE
Cancellation kills Process finishing actions

### ISSUE THREAD

**Issue by Daniel-NP** [Tyrrrz/CliWrap#23]
I'm using the `ExecuteAsync()` in a start-function and call the `cts.Cancel()` from a stop-function. The Cli wraps ffmpeg.exe and the hard `Process.Kill()` prevents the application to finish recording or converting of videofiles.

Maybe you could add a flag like "UseSoftProcessKill" and send the CTRL+C Command this way:
`        public async Task StopScreenRecordAsync()
{
            if (AttachConsole((uint)ffmpegProcess.Id))
            {
                SetConsoleCtrlHandler(null, true);
                try
                {
                    if (!GenerateConsoleCtrlEvent(CTRL_C_EVENT, 0))
                    {
                        return;
                    }
                    while (!ffmpegProcess.HasExited)
                    {
                        await Task.Delay(200);
                    }
                }
                finally
                {
                    FreeConsole();
                    SetConsoleCtrlHandler(null, false);
                }
            }
        }`

Thank you!

**Comment by Tyrrrz** [comment]
Hi
So sending "Ctrl+C" instead of killing the process lets ffmpeg flush the buffer or something? Is there actually a difference between the two?

**Comment by Daniel-NP** [comment]
I dont't really no what ffmpeg does internally, but wenn i kill the process, the recorded file is not playable. When quitting the process wird CTRL+C it gives a working file.

**Comment by Tyrrrz** [comment]
This doesn't look feasible as it would require to use native system API to do that. Also, when an execution is canceled, I think it makes sense that it stops as soon as possible and potentially leaves some work unfinished.

**Comment by Tyrrrz** [comment]
Marking as wontfix since I couldn't find a good enough solution for this and am not convinced that it's worth doing.

**Comment by ahmedtalaat327** [comment]
i think you are using an observable collection in the cli asyn process to collect the data will fix this issue 👀

**Comment by Tyrrrz** [comment]
> i think you are using an observable collection in the cli asyn process to collect the data will fix this issue 👀

This issue is from 2018, it didn't exist back then.
