### ISSUE TITLE
Use IObserver<T>/IObservable<T> for stdin/stdout/stderr

### ISSUE THREAD

**Issue by glenn-slayden** [Tyrrrz/CliWrap#24]
Title of the issue is self-explanatory: as a suggestion, `stdin` might be more flexibly represented by having **CliWrap** provide an `IObserver<String>` . In this vein, your library would then expose `stdout` and `stderr` as each an instance of the push-oriented interface `IObservable<String>`.

These changes would allow for better integration with other standard techniques, tools, and libraries such as *Reactive Extensions*.

**Comment by eltiare** [comment]
I'm guessing communication between the process and C# while the program executes?

**Comment by Tyrrrz** [comment]
I get that, but I meant more as, what benefit would that provide over the existing solution (with delegates)?

**Comment by eltiare** [comment]
Oh hey, look at that: it's even in the readme. Just ignore me. ;)

**Comment by SlowLogicBoy** [comment]
I guess with `IObservable<T>` they want every line returned as an event.
Example:
`cli.Output.Where(line => line.StartsWith("Log:")).Subscribe(OutputLog)`
of course on complete output it wouldn't make sense, but if let's say `cli` process runs infinitely and output is updated in real time, `Observable` pattern becomes very useful, with reactive you can throttle, filter etc.. that output.

I think it shouldn't be difficult to wrap `BuggerHandler` to ether Events, or `Observable` pattern.

**Comment by glenn-slayden** [comment]
Well one obvious advantage is that it would seamlessly interoperate with the [Reactive Extensions](http://reactivex.io/) library. It would also provide instant familiarity and recognition for developers familiar with the `IObservable` paradigm, as well as interoperation with their existing skills, experience and custom tools or environments.

**Comment by Tyrrrz** [comment]
This looks interesting, however, I don't think adding the Rx.net dependency to the base library is a good idea. I would rather have a CliWrap.Rx extension nuget package which adds the functionality via the extension methods like the one @SlowLogicBoy provided.

**Comment by glenn-slayden** [comment]
@Tyrrrz You would not need to add any additional library dependencies. The `IObservable<T>` and `IObserver<T>` interfaces are defined in **mscorlib**. The Reactive extensions library provides additional features ***based on*** those well-known interfaces.

**Comment by Tyrrrz** [comment]
Oh. In that case, sure. :)

**Comment by Tyrrrz** [comment]
Anyone wants to make a PR?

**Comment by Tyrrrz** [comment]
With the new API, implementing this might have become easier, in case someone is still interested.

**Comment by glenn-slayden** [comment]
I'm interested, but a little busy right now... :-/

**Comment by Tyrrrz** [comment]
Hey everyone in the thread. This feature is planned for v3 and you are welcome to leave your feedback on the PR :)
