### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [Tyrrrz/CliWrap#248]
### Details

Is there a plan to include the `PrivacyInfo.xcprivacy` manifest as required by Apple? Please refer to the Apple's document https://developer.apple.com/documentation/bundleresources/privacy_manifest_files for the detailed information.

### Checklist

- [X] I have looked through existing issues to make sure that this feature has not been requested before
- [X] I have provided a descriptive title for this issue
- [X] I am aware that even valid feature requests may be rejected if they do not align with the project's goals
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
CliWrap does not collect or use any user data, and it also doesn't access any Apple-specific native APIs.

Also, [this link](https://developer.apple.com/support/third-party-SDK-requirements/) doesn't work:

![image](https://github.com/Tyrrrz/CliWrap/assets/1935960/72963237-b999-4ceb-a22a-4176442f04da)
