### ISSUE TITLE
Add PipeTargets to redirect to IProgress<string> interface

### ISSUE THREAD

**Issue by vpenades** [Tyrrrz/CliWrap#256]
### Details

.Net has this nice, underated interface called `System.IProgress<T>`   , which is typically used to report percent progress back to a window.  But it can report anything, including strings.

What I usually do is I decorate my windows controls with `IProgress<string>`  so any call to Report(string) can be sent to the appropiate text control.

So it could be nice to be able to redirect the target pipes to an `IProgress<string>` interface.

I am already using these extensions in my own code, but you can probably integrate them into the library in a nicer way, like handling cancellation, EOF, and so on...

```c#
public static PipeTarget ToPipeTarget(this IProgress<string> progress)
{
    async Task _action(Stream origin, CancellationToken cancellationToken)
    {
        var len = 10;

        using var reader = new StreamReader(origin, System.Text.Encoding.UTF8, false, len, true);

        while (true)
        {
            var line = await reader.ReadLineAsync();
            if (line == null) break;

            progress?.Report(line);                    
        }
    }

    return PipeTarget.Create(async (f,c)=> await _action(f,c) );
}        

public static PipeTarget ToPipeTarget<T>(this IProgress<(T context, string msg)> progress, T context)
{
    async Task _action(Stream origin, CancellationToken cancellationToken)
    {
        var len = 10;

        using var reader = new StreamReader(origin, System.Text.Encoding.UTF8, false, len, true);

        while (true)
        {
            var msg = await reader.ReadLineAsync();
            if (msg == null) break;

            progress?.Report((context, msg));
        }
    }

    return PipeTarget.Create(async (f, c) => await _action(f, c));
}
```

### Checklist

- [X] I have looked through existing issues to make sure that this feature has not been requested before
- [X] I have provided a descriptive title for this issue
- [X] I am aware that even valid feature requests may be rejected if they do not align with the project's goals
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Does this not work?

```csharp
var progress = new Progress<string>();

var cmd = Cli.Wrap("foo") | progress.Report;
```

**Comment by vpenades** [comment]
ouch!, I didn't know you could do that!

closing
