### ISSUE TITLE
Is it possible to preserve color output when using ListenAsync and StandardOutputCommandEvent ?

### ISSUE THREAD

**Issue by StefH** [Tyrrrz/CliWrap#257]
### Version

3.6.6

### Platform

.NET 8 / Windows 11

### Steps to reproduce

:one: Create an .NET executable which uses Serilog to write colored output.

:two: Run this executable using:
``` c#
var cmd = Cli.Wrap(Path.Combine(path, exe));

await foreach (var cmdEvent in cmd.ListenAsync(cancellationToken))
{
     switch (cmdEvent)
     {
         case StartedCommandEvent started:
             Console.WriteLine($"Process started; ID: {started.ProcessId}");
             break;

         case StandardOutputCommandEvent stdOut:
             Console.WriteLine($"Out> {stdOut.Text}");
             break;

         case StandardErrorCommandEvent stdErr:
             Console.WriteLine($"Err> {stdErr.Text}");
             break;

         case ExitedCommandEvent exited:
             Console.WriteLine($"Process exited; Code: {exited.ExitCode}");
             break;
     }
}
```

### Details

Expected colors like this:
![image](https://github.com/user-attachments/assets/48396400-f703-4759-9c39-d861f916a8c6)

Actual it's just text without any color.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
The answer is complicated and it depends on how the colors are set in the first place 😁 

If the underlying program is running on Windows and is using the WinAPI to set console colors via [`SetConsoleTextAttribute`](https://learn.microsoft.com/en-us/windows/console/setconsoletextattribute) (or the equivalent framework APIs, such as the `Console.SetForegroundColor(...)` in .NET, for example), then no, it's not possible to retrieve them. The colors are communicated to the console window itself, not as part of the program's output.

If the underlying program is using [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) to set console colors, then it is possible theoretically, as the codes are part of the standard output/error. However, most programs will most likely choose to not output those codes when they detect that the output streams are redirected (which normally implies that the output needs to be clean). In some cases it's possible to override this behavior, but it depends on how the program itself is implemented. Additionally, even if you do manage to extract those codes, you will still need to be able to parse them and re-render them, which is a separate problem in itself (although solvable). Also, #225 may help in running command-line programs with a pseudo terminal, making the former think they have a real console window to interact with.
