### ISSUE TITLE
WindowsSignaler is leaking tmp files

### ISSUE THREAD

**Issue by xpherism** [Tyrrrz/CliWrap#258]
### Details

On Windows calling GetTempFileName results in a 0 size unique file created to ensure the availability of the temp filename. These are not automatically deleted as per documentation (the OS probably will do some cleanup from time to time thou).

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettempfilenamew

Using .NET 7 and below there is limit of 65535 unique temp files names as GetTempFileNameW is used (this limitation is removed in .NET 8+).
If we look and the .NET 8 implementation (which I'm guessing follows the WIN32 implementation somewhat), a loop is use to find an available unique temp filename, which at least as observed for .NET 6 on Windows, will result in very high CPU utilization when nearing the unique temp file name limit as the numbers of name collision becomes very high.

https://github.com/dotnet/runtime/blob/v8.0.8/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs

To avoid leaking temp files and problems that may follow we should remove the original 0 size temp files generated by Path.GetTempFileName. Alternatively we could generate our own temp filenames using GetTempPath and UUID (or similar) to avoid filename collisions.

### Checklist

- [X] I have looked through existing issues to make sure that this feature has not been requested before
- [X] I have provided a descriptive title for this issue
- [X] I am aware that even valid feature requests may be rejected if they do not align with the project's goals
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Hi @xpherism.

Can you please reword your issue title/body so it explains the problem rather than the solution? I see you also created a PR for this issue, the wording there is fine because it focuses on the solution, but the wording in the issue should focus on the problem instead. Thank you!
