### ISSUE TITLE
I need Process Id exposed through CLI/ICLI so I can kill off the underlying long running process

### ISSUE THREAD

**Issue by matthewsheeran** [Tyrrrz/CliWrap#29]
Lets say I am doing an infinite ping.exe -t (actually something more like sqlite3.exe on a SQL script which does some pretty long queries or large updates/inserts) so:
"TokenSource?.Cancel(); Task?.Wait();" on Window Close/Exit doesn't take effect immediately but waits around and takes a long time if the currently executing query line is a long running one before finishing;
Whilst:
"if (this.Thread?.IsAlive == true) this.Thread?.Abort();" is both rather nasty and whilst it appearing immediate actually leaves a stray ping.exe (or sqlite3.exe) sub-process still up and running to cause havoc and locks or multi writer corruption on SQLite files for example.

I need to kill off the ping.exe (or sqlite3.exe) sub-process explicitly using its Process.Id so I am now compiling your code rather than using the DLL through NuGet so I am going to make the change here which I estimate at around a half dozen lines of code plus an external Kill(int Id) routine of my own.

Let me know if you would like the results to reincorporate back into your code case once I get this up tested and working and then I too can switch back to your newer NuGet DLL down the track!

Sound like a plan?

BTW: I moved to CliWrap from another library and this is the only thing missing.  The Stdout and Stderr callbacks work like a treat: I couldn't see any easy way of doing line by line output without this and with any other library it has already made my life significantly easier. SUGGESTION: Make EnableExitCodeValidation and EnableStandardErrorValidation false by default as I started looking at MedallionShell in the beginning when I mistakenly thought that your library like the first I tried wasnt working and was giving me grief at first.

**Comment by matthewsheeran** [comment]
It is weird.
I just tweaked the cancellation token passing but while my application window now closes quickly I still get a stray sqlite3.exe left behind and running afterwards.
Perhaps cancellation doesn't work in your code at that level because I am wrapping your blocking or synchronous Execute with my task which as there is some asynchronous error handling and MessageBox calls all of which work like a treat and displays output and error lines iteratively in a Log Window as the process runs.
I will try not reusing a single token but two separate tokens if I can and calling cancel on yours first next..
The problem has to be something along these lines
Some code summary:

```
                    this.TokenSource = new CancellationTokenSource();
                    this.Task = Task.Factory.StartNew(() =>
                    {
                        this.Thread = Thread.CurrentThread;
                        this.MainWindowIsEnabled(false);
                        int ec = this.ExecuteSQL(stdin);
                        this.MainWindowIsEnabled(true);
                    },
                    //TaskCreationOptions.LongRunning);
                    this.TokenSource.Token);
```
...
```
        private int Execute(string stdin, out string stdout, out string stderr, Action<string> stdoutCallback, Action<string> stderrCallback, CancellationToken token, string path, string arg)
        {
            int ec = -1;
            try
            {
                this.Cli = new Cli(path);
                ExecutionResult er = this.Cli.SetArguments(arg)
                    .EnableExitCodeValidation(false)
                    .EnableStandardErrorValidation(false)
                    .SetStandardInput(stdin)
                    .SetStandardOutputCallback(stdoutCallback ?? this.DummyOutput)
                    .SetStandardErrorCallback(stderrCallback ?? this.DummyOutput)
                    .SetCancellationToken(token)
                    .Execute();
                stdout = er.StandardOutput;
                stderr = er.StandardError;
                ec = er.ExitCode;
            }
            catch (Exception ex)
            {
                string msg = $"{nameof(Dbms)}.{nameof(Execute)} Error running {path} with arguments {arg}";
                Trace.WriteLine($"{msg} {ex}");
                throw new InvalidOperationException(msg, ex);
            }
            return ec;
        }
```
...
```
        private void Window_Closing(object sender, EventArgs e)
        {
            try
            {
                if (this.Task?.IsCompleted == false)
                {
                    this.TokenSource?.Cancel();
                    //this.Task?.Wait();
                    //if (this.Thread?.IsAlive == true)
                    //    this.Thread?.Abort();
                }
            }
            catch { }
        }
```

**Comment by matthewsheeran** [comment]
Yeah it seems to me that if I architect it this way then I do need access to a saved copy of the blocking Process handle in order to kill it off along with cancelling my task in one of the two possible orders in which to do this. Otherwise its ExecuteAsync() and Wait() the ExecutionResult...

**Comment by Tyrrrz** [comment]
Where is the code that passes CancellationToken to your execute method?

**Comment by matthewsheeran** [comment]
There are other nested calls like:
```
 …
ec = this.Dbms.ExecuteSQL(stdin, out stdout, out stderr, this.UpdateChildWindowStdout, this.UpdateChildWindowStderr, this.TokenSource.Token, this.ViewModel.Variables);
...
        public int ExecuteSQL(string stdin, out string stdout, out string stderr, Action<string> stdoutCallback, Action<string> stderrCallback, CancellationToken token, IDictionary<string, string> variables)
        {
               ...
               return this.Execute(stdin, out stdout, out stderr, this.PrefixAndFilterOutput, stderrCallback, token, path, arg);
        }
```
Rather than pull my code to bits and I cant send it all over to you I can build a cut down version along the lines of the ping.exe -t demo from the link above http://stanislavs.org/stopping-command-line-applications-programatically-with-ctrl-c-events-from-net/  Adding CliWrap and another button would do the trick..

I am going to save and expose Process here in my copy of your code...

**Comment by Tyrrrz** [comment]
Okay, cool. I'll wait for the "ping -t" demo. Thanks!

**Comment by matthewsheeran** [comment]
The plot thickens as the ping.exe -t www.google.com Cancellation worked perfectly!
I copy-pasted and edited the existing code with the same structure and parameters..
I will modify so I can do sqlite3.exe instead with my two line import script (which I could probably repeat a bunch of times or continually providing the same stdin line :-)) and the largest .PSV (Pipe rather than CSV) files and try again but it sounds like an sqlite3.exe issue..
(It has just dawned on me that Cancellation must first try SIGINT or Control-C under the hood and without a timeout!? for waiting on the Cancel Request so that a process can cleanup and roll back its query. SQLite IO am certain does and must trap SIGNIT and do this (as well as rolling forward again on startup from a cache) or else its file database would get corrupted every time it is forcibly killed off without this!)

**Comment by matthewsheeran** [comment]
Ah that's worth a try: a Delay in the close and/or a Dispatcher call so we are on the right thread or cause a delay in the close and cause a delay before the Dispatcher closes down. I would presume the CTS.Cancel (CancellationTokenSource) Cancel is Asynchronous.  Thanks for the feedback: I will play a little more and google after following and checking the Token/Cancel first in detail..

**Comment by matthewsheeran** [comment]
Ah beats the hell out of me all I can say is your code gets the Token but the TryKill never actually gets called by it and executed after I Request a Cancel from Window Closing which I have tired with and w/o using the  Dispatcher and an Invoke or BeginInvoke Call and then wait 60 seconds but still the TryKill never gets called unless subsequently call it myself explicitly on the now exposed Process form my two line change to your included Cli.cs case and it all works and has exactly the same effect: I just can't get CancellationTokenSource.Token.Cancel() event/delegate/thread/whatever to fire and do its business: I am thinking Context and Scheduler related and eventually I will work it out but its a case of diminishing returns and I will have to just live with it for now: eventually I will probably work out what it is and make the fix..

**Comment by Tyrrrz** [comment]
Are you using the latest version?

**Comment by Tyrrrz** [comment]
It would be difficult to expose that property due to immutability.
Please get back to me if you ever figure out what was causing this issue.

**Comment by matthewsheeran** [comment]
There is another way: allow the passing of a pre-created Process as parameter in another call that you subsequently pass into CreateProcess and reuse rather creating from scratch then I can still access and Kill it!
