### ISSUE TITLE
Я не могу выполнить выполнить запрос.

### ISSUE THREAD

**Issue by Legenda512** [Tyrrrz/CliWrap#30]
Здравствуйте. С помощью вашей библиотеки я хочу выполнить запросы в консоли cmd. Но у меня не выполняются команды.
Вот пример кода:
string cmd = "ipconfig";
            var result = Cli.Wrap("cmd.exe").SetArguments(cmd).Execute();
            Console.WriteLine(result.StandardOutput);
            Console.ReadKey();
Я хочу выполнить команду ipconfig, но результат работы я не получаю.
И поправьте меня, если я делаю что-то не так.

**Comment by Tyrrrz** [comment]
Try `Cli.Wrap("ipconfig").Execute()` instead

**Comment by Legenda512** [comment]
Огромное спасибо! Вы мне очень помогли!
