### ISSUE TITLE
System.ObjectDisposedException: 'The semaphore has been disposed.' on ICli.ExecuteAndForget()

### ISSUE THREAD

**Issue by petrechitashvili** [Tyrrrz/CliWrap#31]
When I launch an app with ExecuteAndForget and then I close that app, this exception is thrown:

System.ObjectDisposedException: 'The semaphore has been disposed.'

**Comment by petrechitashvili** [comment]
![image](https://user-images.githubusercontent.com/15320885/57527920-f27f2c80-7341-11e9-924f-8a101566ff5f.png)

**Comment by petrechitashvili** [comment]
Applies to any application, not just the one I mentioned

**Comment by Tyrrrz** [comment]
The exception is thrown only after you close the app, as in Explorer or your app?

**Comment by petrechitashvili** [comment]
When you close the app launched by **Cli.Wrap**, not the app which executes the command

**Comment by petrechitashvili** [comment]
Explorer in the example provided

**Comment by Tyrrrz** [comment]
Fixed, a new version should be available on nuget shortly

**Comment by petrechitashvili** [comment]
Thanks!
