### ISSUE TITLE
Pass arguments as list

### ISSUE THREAD

**Issue by krisrok** [Tyrrrz/CliWrap#32]
I've transformed some `Process.Start()` calls into `Cli.Wrap` calls. I've noticed i have to get pretty funky with quotation marks to make it work, at least with one specific application.

Previously i used `ProcessStartInfo.ArgumentList` (which i guess was introduced with netstandard?).

For one process all i had to do is `cli.SetArguments(string.Join(" ", argumentList))` and it worked.

For the other, problematic one i had to try a lot and ended up with a) putting almost (!) every argument set in quotation marks and b) also triple-quotation marks around a "string".
`"\"-D RENDER=\"\"\"SINGLE\"\"\"\""` what previously was just `"-D RENDER=\"SINGLE\""`. 

The argument parser in the other application may be buggy. But still, i don't know why it worked with `ProcessStartInfo.ArgumentList` before.

Looking into your implementation i see you're using "plain old" `ProcessStartInfo.Arguments`. Maybe using the `ProcessStartInfo.ArgumentList` and adding an API like `ICli.AddArgument` would help for these cases.

**Comment by krisrok** [comment]
If I read the documentation correctly the `ProcessStartInfo.ArgumentList` API is only available in netstandard2.1 which seems to be in preview at this time.

So it may be too early to adopt ;)

**Comment by krisrok** [comment]
> A single argument that includes spaces must be surrounded by quotation marks, but those quotation marks are not carried through to the target application. In include quotation marks in the final parsed argument, triple-escape each mark.
[from Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=netframework-4.8)

So it seems the quotation-abomination i described above is expected behaviour. Good thing they added the `ArgumentList` then.

**Comment by Tyrrrz** [comment]
I didn't know they were introducing this, seems useful. We can also try to replicate this ourselves.

**Comment by Tyrrrz** [comment]
Done
