### ISSUE TITLE
CancellationToken not always being honored

### ISSUE THREAD

**Issue by tskarman** [Tyrrrz/CliWrap#37]
Hi, thank you for your work here. I've enjoyed using it for over a year now.

I have generally observed no issues at all with your library around clean-up, signal management, output redirection, native handles, etc.

But the cancellations are often not picked up until after the process has exited and well beyond the original time of cancellation. So I am guessing that's this location: https://github.com/Tyrrrz/CliWrap/blob/37da96ba553ca85d8acc1167b33788fd4a3fdf91/CliWrap/Cli.cs#L302
Sometimes it works, though (immediate cancellation).

The output callbacks keep getting invoked after cancellation and while the process is still running. That's what I'd expect would happen because we don't want to lose process output, but I thought I'd mention it.

This particular invocation is a build script that starts processes of its own (npm, etc.).

Do you have any suspicion what might cause this behavior? Is the cancellation callback guaranteed to get an execution slot or could it be stuck waiting for the `ExecuteAsync` task to yield control?

I noticed that your `TryKill` code is relatively simple and doesn't look at exceptions and other outcomes too hard . May I suggest additions of the following nature? This is taken from some process management code I wrote at some point. Not sure how the API surface maps to what's available on .NET Standard, but I think the general ideas apply.
The important idea being: Check if the termination succeeded or not. And if not handle it in some way.

``` csharp
bool closed;
try
{
    if (!p.HasExited)
    {
        p.CloseMainWindow();
        closed = p.WaitForExit(2000);
    }
    else
    {
        closed = true;
    }
}
catch
{
    closed = false;
}

if (!closed)
{
    try
    {
        if (!p.HasExited)
        {
            p.Kill();

            if (!p.WaitForExit(10000))
            {
                throw new SomeException(
                    $"Most likely failed to terminate process (process ID {processId})'. Termination reason: {reason}. Started with:\n{call}"
                );
            }
        }
    }
    catch (InvalidOperationException) when (process.HasExited)
    {
    }
    catch (Exception ex)
    {
      // ?
    }
}
```

Setup:

CliWrap 2.3.0 in a NetCoreApp 2.2 project running on Windows directly as a Kestrel host.

``` csharp
// in this instance: powershell -File ".\build_client.ps1"
var cli = Cli.Wrap(executable)
    .EnableExitCodeValidation(isEnabled: false)
    .EnableStandardErrorValidation(isEnabled: false)
    .SetWorkingDirectory(workingDirectory.FullName)
    .SetArguments(command.Arguments ?? "")
    .SetCancellationToken(cancellationToken);

cli
    .SetStandardOutputCallback(async stdOutLine =>
    {
        if (httpTracing)
        {
            await logAsync(stdOutLine);
        }
        lock (writeLock1)
        {
            // StreamWriter backed by a file stream
            writerStdOut.WriteLine(GetLine(stdOutLine));
        }
    })
    .SetStandardErrorCallback(async stdErrLine =>
    {
        if (httpTracing)
        {
            await logAsync(stdErrLine);
        }
        lock (writeLock2)
        {
            // StreamWriter backed by a file stream
            writerStdErr.WriteLine(GetLine(stdErrLine));
        }
    });

output = await cli.ExecuteAsync();
```

**Comment by Tyrrrz** [comment]
Hi!
First of all thank you for using my library, it's nice to hear you've had good experiences with it for a year.

The cancellation behavior was designed to try to kill the running process and wait until it exits. It's important that `ExecuteAsync` finishes only when the underlying process terminates. That way you don't have any issues with locked files or other resources not being freed before the execution continues.

Sometimes CliWrap can't kill the process, most of the time because it's already dead or for some other transient reason. I don't think I've encountered a case where the process lived for much longer after that though. As you've noticed the TryKill method is pretty dumb, because .NET doesn't expose a proper reason when a process could not be killed. I decided not to check for HasExited and others in order to avoid race conditions. On top of that, I wasn't sure if throwing an exception in `CancellationTokenSource.Cancel()` was a good idea.

It would be nice if you could somehow record the exception that happens when the process outlives the cancellation as you described.

**Comment by tskarman** [comment]
I will try and come up with additional information/tracing - might take me a few days, though.

What I can tell you now: In the case of the failed cancellations, the process will just keep on running until its natural end. So in the case of this build powershell invocation, it'll keep running for a few more minutes, producing stderr and stdout output as if nothing happened and exit normally. After that natural exit, CliWrap will then `.ThrowIfCancellationRequested`.
So from the outside it appears as if `process.TryKill()` had never been invoked.

**Comment by Tyrrrz** [comment]
I see. It is indeed weird, getting the underlying error would help narrow this down. Would it be possible for you to test with a fork of CliWrap that doesn't swallow exceptions in TryKill?

**Comment by tskarman** [comment]
I just did that and the result is that there is no exception.
This is my instrumentation: https://github.com/tskarman/CliWrap/commit/35a1144f01ad01627b98f09eea674b064d9f54fb

And this is the output:
```
2019-07-09T14:38:21.5814596+00:00 Cli - ExecuteAsync_Register (1)
2019-07-09T14:38:21.5862762+00:00 CliProcess - TryKill (1)
2019-07-09T14:38:21.5886406+00:00 CliProcess - TryKill (2)
2019-07-09T14:38:21.5900262+00:00 Cli - ExecuteAsync_Register (2)
2019-07-09T14:38:59.7489629+00:00 Cli - ExecuteAsync (1)
```

Now that I have the code set up, I'll dig a little deeper. Just wanted to let you know.

**Comment by tskarman** [comment]
I'll have to stop for today. The last result is in https://github.com/tskarman/CliWrap/commit/c043ed70b259b69047069a263670b5ad14788874

With that code the process will correctly terminate immediately. So it looks like the process doesn't really exit completely until the output listeners are gone.
It's strange because `_nativeProcess.HasExited == true` after the `.Kill()`. But looking at this https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L200 that's maybe not too suprising after all.

**Comment by Tyrrrz** [comment]
Huh, interesting. If that's the case, we can unsubscribe from events when killing the process.

**Comment by Tyrrrz** [comment]
Can you check if unsubscribing from output listeners resolves the issue?

**Comment by tskarman** [comment]
I tried and didn't come up with a stable solution. I ran into new issues.
I am not sure when I'll get a chance to have another look.

But I'd thought I'd share a minimal repro.

I created this in LINQPad and attached that script as a ZIP file below. But the code is straight-forward and has only CliWrap and Windows as a dependency. I tried on an up-to-date Windows 10 as well as a Windows Server 2012 T2:

``` csharp
async Task Main()
{
	var executable = @"powershell";

	using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2))) {
	var ct = cts.Token;

		using (var ctr = ct.Register(() =>
		{
			Console.WriteLine($">> observed cancellation");
		}))
		{
			var cli = Cli.Wrap(executable)
				.EnableExitCodeValidation(isEnabled: false)
				.EnableStandardErrorValidation(isEnabled: false)
				.SetArguments(@"-NoProfile -Command ""ping -n 5 127.0.0.1""")
				.SetCancellationToken(ct);

			cli
				.SetStandardOutputCallback(stdOutLine =>
				{
					Console.WriteLine("     " + stdOutLine);
				})
				.SetStandardErrorCallback(stdErrLine =>
				{
					Console.WriteLine("     " + stdErrLine);
				});

			try
			{
				var output = await cli.ExecuteAsync();
				Console.WriteLine($">> observed normal end of execution");
			}
			catch (Exception)
			{
				Console.WriteLine($">> observed end of execution with exception");
			}
		}
	}
}

```

The output:
```
     
     Pinging 127.0.0.1 with 32 bytes of data:
     Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
     Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
>> observed cancellation
     Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
     Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
     Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
     
     Ping statistics for 127.0.0.1:
         Packets: Sent = 5, Received = 5, Lost = 0 (0% loss),
     Approximate round trip times in milli-seconds:
         Minimum = 0ms, Maximum = 0ms, Average = 0ms
>> observed end of execution with exception
```

LINQPad script: 
[cliwrap-issue37-repro-linqpad.zip](https://github.com/Tyrrrz/CliWrap/files/3377776/cliwrap-issue37-repro-linqpad.zip)


Can you confirm the behavior?

Of note: it works correctly if you just call `ping` directly instead of via a PowerShell script. But since we are interested in a repro...

**Comment by Tyrrrz** [comment]
Yes, I'm able to reproduce it with your code.
Maybe powershell does something weird, I'll try to investigate.

**Comment by Tyrrrz** [comment]
Looks like unsubscribing and releasing end-of-output signals fixes it.
It seems that `TryKill` does kill the process, but the output streams are not yet closed at this point and still have data in them. This is really weird, I guess it comes from how Windows handles stdout/stderr, I don't know.

**Comment by tskarman** [comment]
I think the issue is that the process is actually killed but any child process it spawned is not. And what happens is that the output redirection is still attached to any spawned and active child process.
And so that stalls the shutdown of `CliProcess`.

A similar situation arises with:
- `cmd /C ping -n 5 127.0.0.1`
- `cmd /C ping -n 5 127.0.0.1 && ping -n 10 127.0.0.1`

So detaching output handlers def. makes sense.

What it won't "fix" is that the child process will keep running no matter the parent `.Kill()`. That's something that the `Process` API doesn't offer.
It would prob. involve `P/Invoke` into the job object Win32 APIs. Or I might be able to adjust my PowerShell invocation to queue itself as a job. Job processes take down their child process with them.

**Comment by Tyrrrz** [comment]
Ah, so in that case `cmd` is killed but `ping` is still alive and the stdout/stderr is redirected from `ping` to `CliWrap`? That makes sense.

>What it won't "fix" is that the child process will keep running no matter the parent `.Kill()`.

Does it also happen when you're using `powershell` to run a ps1 script? Does it create a child process for the script execution?

**Comment by tskarman** [comment]
A simple script execution is fine (e.g. try `-Command ""Test-Connection 127.0.0.1 -Count 10""`).
But my uses often involve spawning child processes. And in build scripts it's important to capture the child process outputs as well.

Thanks for the quick fix. I will give it a try.

I am a bit hesitant about the following aspects:
- The stderr/stdout outputs are not necessarily drained
- The semaphore might get released more than once. But that prob. won't cause exceptions
- I am not sure which guarantees can be made about the output/error handler delegates. They are never explicitly `-=`d. I guess it's fine as long as `Process::Dispose()` is called.

**Comment by Tyrrrz** [comment]
>The stderr/stdout outputs are not necessarily drained

This indeed sounds like it could be problematic.

>The semaphore might get released more than once. But that prob. won't cause exceptions

I've made sure it's not an issue.

>I am not sure which guarantees can be made about the output/error handler delegates. They are never explicitly -=d. I guess it's fine as long as Process::Dispose() is called.

Once you `Dispose`, it stops listening to events and shouldn't (according to API) trigger the handler delegates. The lifetime of `CliProcess` (and by extension `_nativeProcess`) is confined with `ExecuteAsync` so there shouldn't be any reference leaks.

**Comment by tskarman** [comment]
I just did a quick experiment with the native Job Objects (https://docs.microsoft.com/en-us/windows/win32/procthread/job-objects).

When creating a job with the `_nativeProcess` and destroying it on `.TryKill()/.Dispose()` the child process(es) get torn down immediately and so does the output. So the issue doesn't appear in that situation (even without your fix).
This is what's expected - it just further supports the suspicion. I just wanted to add the information here.

How interested are you in having Win32-specific code in your library? I am only asking because I absolutely need to have that functionality in some (not all) use cases. I am pondering whether to implement that for my own usage only as a separate library or integrating it with `CliWrap`.
Really all that is needed to implement it is access to the `_nativeProcess`.
But exposing `_nativeProcess` publicly prob. goes against your idea with the library?

**Comment by Tyrrrz** [comment]
I'm generally against the idea of adding platform-specific logic to CliWrap, if possible, and also want to preserve the level of abstraction it currently has.
But if you find a solution that involves Win32 API, please post it here anyway, maybe I'll think of a way to make the architecture more extensible in the future, allowing platform-specific code in a separate binary/NuGet package.
