### ISSUE TITLE
Provide some way to get Process Id

### ISSUE THREAD

**Issue by aersamkull** [Tyrrrz/CliWrap#40]
Hi there! Thanks for this greaty utility! It makes my life a lot easier :) 
Is there a chance to get some after process Start Callback in order to get the process Id right after the start? I'd do a PR if desired :)

**Comment by aersamkull** [comment]
As I need it, i just implemented it :)

**Comment by Tyrrrz** [comment]
Hey there.
Can you explain in more detail why you need this feature?

**Comment by aersamkull** [comment]
Well, the idea is that I can log this ProcessId to some db or file. If I'd like to kill the process from outside I can easily identify it. I actually use the cancellation token if ever possible, but we have to be really sure to be able to kill the job from outside if nothing else works.

**Comment by Tyrrrz** [comment]
Makes sense.
