### ISSUE TITLE
Wrap method on ICli interface missing

### ISSUE THREAD

**Issue by JacoJordaan** [Tyrrrz/CliWrap#42]
It looks like the Wrap method on the ICli interface is missing. 
It is not possible to do DI or mocking on the Wrap method via interface.

**Comment by JacoJordaan** [comment]
Apologies, I see the wrap method is just creating a new instance.

**Comment by Tyrrrz** [comment]
That's right, it's just a convenience method that makes execution chain a little more fluent.
