### ISSUE TITLE
IAsyncEnumerable<string> for stdout?

### ISSUE THREAD

**Issue by Daniel15** [Tyrrrz/CliWrap#45]
In addition to `SetStandardOutputCallback`, it would be useful to have a method that returns an `IAsyncEnumerable<string>`, to allow us to use `await foreach` to iterate over stdout/stderr as it arrives.

More info in `IAsyncEnumerable`: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream

**Comment by Tyrrrz** [comment]
This is planned for v3 and you're welcome to leave your feedback on the linked PR :)
