### ISSUE TITLE
Cannot launch an interactive process with Cli.Wrap

### ISSUE THREAD

**Issue by aniongithub** [Tyrrrz/CliWrap#48]
Because of [this](https://github.com/Tyrrrz/CliWrap/blob/master/CliWrap/Internal/CliProcess.cs#L40) line of code, it's currently impossible to use CliWrap to launch processes that need/allocate a PTY.

Help?

**Comment by Tyrrrz** [comment]
What exactly do you mean by interactive processes? Ones that interrupt execution waiting for user input?

**Comment by aniongithub** [comment]
Yes, that's right.

**Comment by Tyrrrz** [comment]
You can try setting standard input when you launch a CLI.

**Comment by Tyrrrz** [comment]
Did that help?

**Comment by goncalo-oliveira** [comment]
I see this issue is closed, but I'm having a similar difficulty and didn't see a way to sort it out. The child process is interactive and requires use of STDIN, mainly to read Ctrl+C to break the execution.

I've tried doing something like this

```csharp
            await using var stdOut = Console.OpenStandardOutput();
            await using var stdErr = Console.OpenStandardError();
            await using var stdIn = Console.OpenStandardInput();

            var cmd = CliWrap.Cli.Wrap( appName )
                .WithArguments( args )
                .WithStandardInputPipe( PipeSource.FromStream( stdIn ) )
                .WithValidation( CliWrap.CommandResultValidation.None ) | ( stdOut, stdErr );

            var result = await cmd.ExecuteAsync();
```

On linux this seems to work fine, but on Windows, although the STDOUT and STDERR work fine, STDIN doesn't work as expected. Maybe I'm missing somthing... any suggestion?

**Comment by Tyrrrz** [comment]
> I see this issue is closed, but I'm having a similar difficulty and didn't see a way to sort it out. The child process is interactive and requires use of STDIN, mainly to read Ctrl+C to break the execution.
> 
> I've tried doing something like this
> 
> ```cs
>             await using var stdOut = Console.OpenStandardOutput();
>             await using var stdErr = Console.OpenStandardError();
>             await using var stdIn = Console.OpenStandardInput();
> 
>             var cmd = CliWrap.Cli.Wrap( appName )
>                 .WithArguments( args )
>                 .WithStandardInputPipe( PipeSource.FromStream( stdIn ) )
>                 .WithValidation( CliWrap.CommandResultValidation.None ) | ( stdOut, stdErr );
> 
>             var result = await cmd.ExecuteAsync();
> ```
> 
> On linux this seems to work fine, but on Windows, although the STDOUT and STDERR work fine, STDIN doesn't work as expected. Maybe I'm missing somthing... any suggestion?

By not working fine, what do you mean? One thing is that on Windows the console streams don't support cancellation so they are effectively infinite.

Sending Ctrl+C (or other signals) is also currently impossible using .NET altogether.

**Comment by Tyrrrz** [comment]
Keyboard input is not sent through stdin, it's passed to the terminal window directly

**Comment by goncalo-oliveira** [comment]
> Keyboard input is not sent through stdin, it's passed to the terminal window directly

Oh, of course. That makes sense... Then why would they keyboard input work (on the child process) when running on linux, but not when running on windows?

This is not an issue with CliWrap, in reality, because if I use `Process.Start` I get the same behaviour.

**Comment by Tyrrrz** [comment]
> Then why would they keyboard input work (on the child process) when running on linux, but not when running on windows?

I don't know the answer to that unfortunately 🤷🏻‍♂️

**Comment by moh-hassan** [comment]
>Then why would they keyboard input work (on the child process) when running on linux, but not when running on windows?


I test the [Alexey code](https://github.com/Tyrrrz/CliWrap/issues/48#issuecomment-981768015) with an interactive console app   and it's **working fine in both Windows and Linux (Ubuntu 18.04).**
I used CliWrap version 3.3.3. The parent  app is net 5.0 project and the child app is net5.0 project. Both projects are build on the Linux machine.
