### ISSUE TITLE
Set environment variables

### ISSUE THREAD

**Issue by pipe01** [Tyrrrz/CliWrap#5]
First of all, just wanted to say good job on this project, it's awesome and I will undoubtedly use it on any of my upcoming projects!

My request is to be able to set environment variables for the process. Exposing `ProcessStartInfo.EnvironmentVariables` would be enough for the job.

**Comment by Tyrrrz** [comment]
Hey, thanks for the kind words.

I saw you already started working on this, so submit PR as soon as you're done so I can review it. :)

**Comment by pipe01** [comment]
Sure!

**Comment by pipe01** [comment]
#6 There you go

**Comment by Tyrrrz** [comment]
Ok it's now in master, i found a nice way to integrate it with existing API and it also has tests now.
