### ISSUE TITLE
Process exit and EventStream

### ISSUE THREAD

**Issue by MindWrapper** [Tyrrrz/CliWrap#53]
I've been playing with this example:

https://github.com/Tyrrrz/CliWrap#executing-a-command-as-an-event-stream

And found out that is process exits with non-zero exit code, then exception is thrown and `case ExitedCommandEvent exited:`  is never executed.  
Is it expected?

**Comment by Tyrrrz** [comment]
Hi.

Yes, that's expected, this way the behavior is inline with other execution models in that it respects the configured validation option.

If you want to have it off, you can use `WithValidation(CommandResultValidation.None)`.
