### ISSUE TITLE
Create TaskCompletionSource with TaskCreationOptions.RunContinuationsAsynchronously

### ISSUE THREAD

**Issue by georg-jung** [Tyrrrz/CliWrap#54]
After [looking for a good library doing basically what CliWrap does](https://gist.github.com/georg-jung/3a8703946075d56423e418ea76212745#gistcomment-3247475) I think it's by far the best solution I've seen so far, thanks for the great work!

While reading [some source code](https://github.com/Tyrrrz/CliWrap/blob/5127487aa83b6810ca268ca504246b21adf203f9/CliWrap/Internal/ProcessEx.cs#L11) stumbled upon this line 

    private readonly TaskCompletionSource<object?> _exitTcs = new TaskCompletionSource<object?>();

and had to think of [David Fowler's async guidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously). I don't know if you considered this and I'm not at all deep enough into your code to know if it might not make sense in this case, but I thought I'd drop a note.

**Comment by Tyrrrz** [comment]
Hi, I had no idea about this. Sounds like a terrible design oversight to me, I would have never considered that to be the default behavior.

If you want, you're welcome to submit a PR to fix this.

**Comment by georg-jung** [comment]
I guess (but really don't know) that's due to other defaults when the TCS is creating the Task itself and those make more sense in other cases (i.e. forcing async execution might have some overhead I guess). Probably they noticed the downsides of this default after releasing the API. When setting up a PR I noticed that the option is actually unavailable in NS2.0 (but available in all the other relevant targets). Thus, afaik this is only fixable for the other targets using a compiler condition. Looking further into it this seems to be only relevant [for this one use of the TCS](https://github.com/Tyrrrz/CliWrap/blob/5127487aa83b6810ca268ca504246b21adf203f9/CliWrap/Command.cs#L250).

Now, how WhenAll is implemented and thus if this is relevant is beyond my knowledge. I'll still send the PR for reference (#55) but I'm currently not sure what's the right way to proceed. On one hand, not doing this makes possible future usages of the TCS's task kind of dangerous and would lead to hard to debug situations then. On the other hand merging fixes this for some platforms but keeps others (possibly in the future) broken.

**Comment by Tyrrrz** [comment]
Are you sure? I can see it's available in .NET Standard 2.0. It's only .NET Framework where it's not supported before 4.6 (but we don't target it anyway).

**Comment by georg-jung** [comment]
Hmm, seems like you're right. Strange. IntelliSense first told me it wouldn't be available, but doesn't tell me anymore now. It compiles fine too. A small test class lib project targeting only NS2.0 plus a unit test using it executes fine too. [This](https://apisof.net/catalog/System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously) supports it too. I'll change the PR. Strange enough, I really don't know how this happened.

**Comment by Tyrrrz** [comment]
No worries ;)
