### ISSUE TITLE
Console.ReadKey problems

### ISSUE THREAD

**Issue by KoalaBear84** [Tyrrrz/CliWrap#56]
Hi, thanks for the library. I'm trying to use it to automate something.

I have a 'client' application that has the following code:
```cs
while (true)
{
	try
	{
		switch (Console.ReadKey(true).Key)
		{
		}
	} catch {}
}
````

Because of this, I get as fast as it can the following errors:
```
Out> 2020-04-15 16:44:12.9287  [1] ERROR Command.ProcessConsoleInput Error processing action System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
Out>    at System.ConsolePal.ReadKey(Boolean intercept)
Out>    at System.Console.ReadKey(Boolean intercept)
Out>    at ClientApplication.Command.ProcessConsoleInput() in Command.cs:line 45
```

Can something be done by giving the client application a 'pipe' to read from?

The most beautiful solution would be if this could be redirected from the host application, thanks!

**Comment by Tyrrrz** [comment]
Try

```csharp
Console.In | Cli.Wrap(...)
```

**Comment by KoalaBear84** [comment]
Thanks for your quick response.

Turned this:
```csharp
Command command = Cli.Wrap("consoleapp.exe")
  .WithArguments($"-q --url {url}")
  .WithValidation(CommandResultValidation.None);
```

Into this:
```csharp
Command command = Console.In | Cli.Wrap("consoleapp.exe")
  .WithArguments($"-q --url {url}")
  .WithValidation(CommandResultValidation.None);
```
or this:
```csharp
Command command = (Console.In | Cli.Wrap("consoleapp.exe"))
  .WithArguments($"-q --url {url}")
  .WithValidation(CommandResultValidation.None);
```

And get the following compile error:
`Operator '|' cannot be applied to operands of type 'TextReader' and 'Command'`

I have no experience with this | construct.

When I do this:
```csharp
Command command = Cli.Wrap("consoleapp.exe")
  .WithArguments($"-q --url {url}")
  .WithStandardInputPipe(Console.In)
  .WithValidation(CommandResultValidation.None);
```

I get this error:
`Argument 1: cannot convert from 'System.IO.TextReader' to 'CliWrap.PipeSource'`

**Comment by Tyrrrz** [comment]
My bad, I forgot it's a `TextReader`. In that case `Console.OpenStandardInput()` should work. Your input is successfully redirected but it's likely that your app is not waiting for any data (as `Console.ReadLine()` would, for example).

Maybe what you actually need is:

```csharp
var data = Console.ReadLine();
var command = data | Cli.Wrap("consoleapp.exe")
  .WithArguments($"-q --url {fixedUrl}")
  .WithValidation(CommandResultValidation.None);
```

I'm not sure how `Console.ReadKey()` works and what it expects to receive in stdin.

**Comment by KoalaBear84** [comment]
`Console.ReadKey()` does wait for input, but it is 'direct' input, not waiting for an enter.

Windows Terminal does work with this, which is a little like CliWrap 😂

I haven't really found a working example. I did found this simple example, but does not work for ReadKey: https://gist.github.com/antopor/5515bed636c3d99395ea

**Comment by Tyrrrz** [comment]
I really doubt you can make `Console.ReadKey()` work without an actual terminal.

**Comment by KoalaBear84** [comment]
I'll close this for now, it's still no clear for me how it should work with CliWrap to redirect anything, will continue if I have the time. Thanks!
