### ISSUE TITLE
How to cancel ongoing process?

### ISSUE THREAD

**Issue by warheat1990** [Tyrrrz/CliWrap#57]
Sorry for beginner question, I used this library to create an automated Build (msbuild.exe), my question is let's say for some reason it's taking too long, and I want to cancel the process. How do I do that?

My current app is created using SignalR so every user can see the terminal output on real time.

```
var cli = Cli.Wrap(command).WithValidation(CommandResultValidation.None).WithArguments(arguments);
            var output = "";

            await foreach (var cmdEvent in cli.ListenAsync())
            {
                switch (cmdEvent)
                {
                    case StartedCommandEvent started:
                        output = "ProcessID : " + started.ProcessId;
                        break;
                    case StandardOutputCommandEvent stdOut:
                        output = stdOut.Text;
                        break;
                    case StandardErrorCommandEvent stdErr:
                        output = stdErr.Text;
                        break;
                    case ExitedCommandEvent exited:
                        output = "ExitCode : " + exited.ExitCode;
                        break;
                }

                //send to all client
                await Clients.All.SendAsync("BuildOutput", output);
            }
```

**Comment by Tyrrrz** [comment]
You would use a cancellation token as described here:

https://github.com/Tyrrrz/CliWrap#timeout-and-cancellation

**Comment by ahmedtalaat327** [comment]
@Tyrrrz  I've searched there is no solution to stop proc manually , all ex. are automated?

**Comment by Tyrrrz** [comment]
@ahmedtalaat327 what do you mean by "manually"?

**Comment by ahmedtalaat327** [comment]
> @ahmedtalaat327 what do you mean by "manually"?

Simply how to stop long running process ?

**Comment by ahmedtalaat327** [comment]
> @ahmedtalaat327 what do you mean by "manually"?

Fixed by holding the Id of each process
![image](https://github.com/user-attachments/assets/dbf584b9-80c9-45b3-8726-3c4c66296d38)
