### ISSUE TITLE
DebuggerDisplay for CommandEvents

### ISSUE THREAD

**Issue by Piedone** [Tyrrrz/CliWrap#58]
A tiny improvement would be to add `[DebuggerDisplay("{Text}")]` to `StandardOutputCommandEvent` and `StandardErrorCommandEvent`. This way when you're looking at command outputs in the debugger you'd see their contents right away, not just after opening the `Text` property.

What do you think? I can submit a PR.

**Comment by Tyrrrz** [comment]
Go ahead.
