### ISSUE TITLE
Piping ffmpeg into another process doesn't seem to do anything

### ISSUE THREAD

**Issue by Wildenhaus** [Tyrrrz/CliWrap#61]
I am trying to achieve the following pipe with CliWrap:

```
ffmpeg.exe -y -i "C:\input.mp4" -pix_fmt yuv420p -f yuv4mpegpipe - | aomenc.exe -v -w 1920 -h 1080 --passes=2 --pass=1 --fpf=".\out.stats" -t 1 --cq-level=30 --end-usage=q -o ".\out.ivf" -
```
This command works as it should in Command Prompt and PowerShell.

To do this, I am using CliWrap like so:

```
var ffProcess = Cli.Wrap( "C:\\ffmpeg.exe" ).WithArguments( ffArgs );
var aomProcess = Cli.Wrap( "C:\\aomenc.exe" ).WithArguments( aomArgs );
await ( ffProcess | aomProcess ).ExecuteBufferedAsync();
```

This launches the processes, but seems to just sit there until terminated. When launched manually, these two processes take up 50% CPU, but with CliWrap, they just sit there at 0%. This happens with both `ExecuteAsync()` and `ExecuteBufferedAsync()`.

Ideally, I would like to use `ListenAsync()` so that I can read from the StdErr of `aomenc.exe` and parse the progress it outputs, but that doesn't seem to work either.

**Comment by Tyrrrz** [comment]
Can you give a link where I can download the `aomenc.exe` build you've used?

**Comment by Wildenhaus** [comment]
> Can you give a link where I can download the `aomenc.exe` build you've used?

Sure! Both my ffmpeg and aomenc builds were sourced from [here](https://jeremylee.sh/bin.html).

**Comment by Wildenhaus** [comment]
Apologies for the double post, but I have found a solution and thought it warranted a separate post.

I was playing around with piping using `System.Diagnostics.Process` and I noticed that if you redirect StandardInput along with StandardError and/or StandardOutput, it causes a deadlock, but ONLY if you are awaiting `Stream.CopyToAsync()`. Changing these to be Tasks and awaiting them after the process exits fixes the problem.

**Command.cs:260**
```
private async Task<CommandResult> ExecuteAsync( ProcessEx process, CancellationToken cancellationToken = default )
{
  using var _ = process;

  process.Start();

  // Register cancellation
  using var cancellation = cancellationToken.Register(() => process.TryKill());

  // Handle stdin pipe
  var copyInputTask = StandardInputPipe.CopyToAsync(process.StdIn, cancellationToken);
  var copyOutputTask = StandardOutputPipe.CopyFromAsync( process.StdOut, cancellationToken );
  var copyErrorTask = StandardErrorPipe.CopyFromAsync( process.StdErr, cancellationToken );

  // Handle stdout/stderr pipes and wait for exit
  await process.WaitUntilExitAsync();

  if( process.ExitCode != 0 && Validation.IsZeroExitCodeValidationEnabled() )
    throw CommandExecutionException.ExitCodeValidation( TargetFilePath, Arguments, process.ExitCode );

  await Task.WhenAll( copyInputTask, copyOutputTask, copyErrorTask );
  return new CommandResult( process.ExitCode, process.StartTime, process.ExitTime );
}
```

**PipeTarget.cs:105**
```
public override Task CopyFromAsync(Stream source, CancellationToken cancellationToken = default) =>
            source.CopyToAsync(_stream, cancellationToken);
```

There's one issue with this approach: `ffmpeg` closes after it is done piping the file, but `aomenc` remains open, and I am not sure why. The output appears to be in order though.

**Comment by Tyrrrz** [comment]
Good point. I'll try to see if I can reproduce it in tests. Moving the stdin pipe out of `using` might cause a deadlock in another scenario though :(

**Comment by Tyrrrz** [comment]
Reproduced it in tests and fixed. New release should be out shortly.

I didn't test it with your exact setup but I'm pretty sure that was the same bug.

**Comment by Tyrrrz** [comment]
@Wildenhaus have you had time to try out the new version? Did it work?
