### ISSUE TITLE
How to interact with prompts

### ISSUE THREAD

**Issue by GFoley83** [Tyrrrz/CliWrap#64]
Is it possible to answer multiple command prompts using CliWrap?
![image](https://user-images.githubusercontent.com/838788/81551830-988ec800-93d6-11ea-882c-aa3858589e25.png)
I'd like to automate configuring RClone but the challenge is that there are multiple questions in the setup and long delays in between each steps (while API calls are made in the background).

Obviously I can figure out the answers to all the prompts ahead of time, I'm just not sure how I'd accomplish triggering the prompt answers with CliWrap.

**Comment by Tyrrrz** [comment]
If the target processes simply uses an equivalent of `Console.ReadLine()` for each prompt then you can just "preload" the answer in the stdin, one per each line.

**Comment by Tyrrrz** [comment]
That's assuming when you type n/s/q you also need to press Enter. If it just waits for a keypress then it's unfortunately not possible to automate because we'd need to send a real key press signal to the console window.

**Comment by GFoley83** [comment]
Pretty sure it waits for you to press enter. I'll test tomorrow.

**Comment by Tyrrrz** [comment]
Did you manage to get it working?
