### ISSUE TITLE
Deadlocking issue with lots of stdout and stderr

### ISSUE THREAD

**Issue by scott-mac** [Tyrrrz/CliWrap#65]
We're using CliWrap to invoke R scripts for data modelling (R is a stats/data analysis language). I'm using the event stream usage example that you have posted on Github like this:

```
           await cmd.Observe().ForEachAsync(cmdEvent => {
                    switch (cmdEvent) {
                        case StandardOutputCommandEvent stdOut:
                            sbOut.AppendLine($"{stdOut.Text}");
                            break;
                        case StandardErrorCommandEvent stdErr:
                            sbErr.AppendLine($"{stdErr.Text}");
                            break;
                        case ExitedCommandEvent exited:
                            //handle exit-code etc
                            break;
                    }
                });
```

All I do for StandardOutputCommandEvent and StandardErrorCommandEvent  is capture the text to 2 different string builders which I dump to a log periodically so we can actually see the script progress in real time. What seems to be happening though is that something locks up and the event stream stops capturing. So I get no further output and the ExitedCommandEvent never fires so it never runs my completion and cleanup code, to my program it just appears as if it is still running. The thing is, the script actually does complete it's execution because at the end it writes out several files and I've verified that those are being written even when the code above hangs.

The other clue is that when I was testing this, it was very sporadic: sometimes it would run to completion, sometimes it would hang-up. As best I can tell the issue seems to be with high volume messages in quick succession. When I would test with a small dataset, the RScript will rip though the numbers very quickly (only 1-2 mins) and since it is quite verbose in it's messaging, you'll get a lot of output happening quickly. But with the large datasets it takes R much longer to execute each step in the script so the messages come though much slower over 30-40 mins which doesn't seem to cause an issue. Not sure if this is a deadlocking issue, but I did see a mention of that in the last release notes. Thank you

**Comment by Tyrrrz** [comment]
Hi. Are you using the latest version, CliWrap v3.0.2?

**Comment by scott-mac** [comment]
Sorry, I should have mentioned that. 
Yes I am using v3.0.2

**Comment by Tyrrrz** [comment]
Hmm, interesting. There shouldn't be a deadlock because of high rate of messages.

Can you try running it via `ExecuteAsync()` without any pipes instead of `ListenAsync()` and see if it makes any difference?

You could also do something like this for your scenario instead of event streaming:

```csharp
var sbOut = new StringBuilder();
using var fileOut = File.Create("...");

var sbErr = new StringBuilder();
using var fileErr = File.Create("...");

var stdOutPipe = PipeTarget.Merge(
     PipeTarget.ToStringBuilder(sbOut),
     PipeTarget.ToStream(fileOut)
);

var stdErrPipe = PipeTarget.Merge(
     PipeTarget.ToStringBuilder(sbErr),
     PipeTarget.ToStream(fileErr)
);

var command = Cli.Wrap(...) | (stdOutPipe, stdErrPipe);

var result = await command.ExecuteAsync();
```

Not sure if it makes a difference.

Ideally, if you can find a way to reproduce it consistently on some R script or something, I could try running it myself to see what could be the problem.

**Comment by Tyrrrz** [comment]
Also, can you give an example of the output from stdout/stderr that it writes when CliWrap hangs?

**Comment by scott-mac** [comment]
There's no rhyme or reason to when it hangs, I tested across multiple datasets of different sizes so depending on how fast it was working thru the script it would stop at different points. There's one section in the middle where it does the variable selection process and it spits out a bunch of lines like this:

 [1] "VAR3_20_0_10" "VAR3_30_0_10" "VAR3_40_0_10" "VAR3_50_0_10" "VAR3_60_0_10"
 [6] "VAR3_70_0_10" "VAR3_80_0_10" "VAR3_90_0_10" "VAR3_10_0_20" "VAR3_20_0_20"
[11] "VAR3_30_0_20" "VAR3_40_0_20" "VAR3_50_0_20" "VAR3_60_0_20" "VAR3_70_0_20"
[16] "VAR3_80_0_20" "VAR3_90_0_20" "VAR3_10_0_30" "VAR3_20_0_30" "VAR3_30_0_30"

It would often hang around this part with small-to-medium sized datasets.

I will definitely try your piping example though and let you know if that solves it for me. Am I understanding the PipeTarget.Merge operation correctly - that it will pipe the output to both destinations...sort of like how NLog allows you to define multiple targets for logging (i.e. file, database, event log etc)? Thank you for the help. I will report back tomorrow

**Comment by Tyrrrz** [comment]
That's weird. I can't think of any reason why that could be happening.

> Am I understanding the PipeTarget.Merge operation correctly - that it will pipe the output to both destinations

Yes, that's the idea behind it. You can read more about it in the readme: https://github.com/Tyrrrz/CliWrap#piping

The piping model is pretty versatile.

**Comment by scott-mac** [comment]
OK I tried your example exactly as above with the StringBuilder and File pipes. Unfortunately I get the same behavior. But writing to the files did provide another clue that I didn't see before when I was only using StringBuilders. Every time it hangs no matter what dataset I use to test with, the size of the stdErr file is always 4096... which I'm sure you recognize immediately as the default buffer size for most streams in .NET.  Interestingly the size of the stdOut file, while it varied depending on which dataset I chose to run was always a multiple too, for example:

Dataset1 - stdOut = 16384 (4096 x 4) stdErr = 4096 
Dataset2 - stdOut = 28672 (4096 x 7) stdErr = 4096

Next I tried them one at a time using the WithStandardOutputPipe and WithStandardErrorPipe options. Results were:

stdErr only - 4096
stdOut only - 28672

I then ran it with neither attached but still no luck getting it to run successfully. Hopefully this gives you some clues.

**Comment by Tyrrrz** [comment]
That definitely looks suspicious. I can't find right off the bat where 4096 could be used as most of the buffer sizes are overridden to 81920 (copying) or 1024 (reading characters).

The fact that it also didn't work with neither of pipes configured suggests that the problem is actually not with the pipes.

What does it write to stderr exactly? Are there newlines in-between or is it just a one long sequence of strings?

Also, am I right in understanding you were able to get it to reproduce consistently? At least the multiples of 4096 occurrence?

**Comment by scott-mac** [comment]
yeah there are line feeds in there, it's pretty standard console-type output. Typically in these scripts you have multiple print statements to indicate what you are doing where so that if something fails you can track it down. Also, you tend to use a lot of packages for various things (e.g. database access, stats, string manipulation etc) so each of those will often output their own messaging. When I was playing with it earlier I had a script that was capturing output until the very last few lines so as a test I just commented some things out and bang it just worked!

As far as the 4096, I've ran a dozen tests now and the stdErr is always 4096 and the stdOut is always a multiple thereof so that definitely caught my attention.

**Comment by Tyrrrz** [comment]
> When I was playing with it earlier I had a script that was capturing output until the very last few lines so as a test I just commented some things out and bang it just worked!

What was that you had to comment out to get it working?

> As far as the 4096, I've ran a dozen tests now and the stdErr is always 4096 and the stdOut is always a multiple thereof so that definitely caught my attention.

Is it also multiples of 4096 if you just run the script from command line and redirect output to a file?

**Comment by scott-mac** [comment]
> What was that you had to comment out to get it working?

I didn't actually comment out any functionality in the script but what you can do in R is wrap any function call in a suppressMessages block and it will ignore most of the output from that call and not write it to stdout/stderr. I chose a couple that were more verbose and that fixed it.

> Is it also multiples of 4096 if you just run the script from command line and redirect output to a file?

I ran a bunch of tests this morning, calling the script from command line and directing output to files. When I do that I get the full expected output. I then wrote a console app to just generate random lines and write them to stdOut/stdErr and tested that. What I discovered was that the files generated are ALWAYS a multiple of 4096 so clearly this is an OS thing where it writes in 4K chunks. So very unlikely this has anything to do with your code.

Next I took the output of calling the script from cmd line and I wrote a little console app that reads those files and simply iterates each line and writes it to stdOut and stdErr. Here's what I found. When I CliWrap that console app and run it it does not hang up, I get a 0 exit code as expected. But here's the thing, the files it generates are truncated! Just like with running my script, it stops writing at a certain point and it is always the same point that it stops at for a given file. So it seems like what is probably happening is you are not flushing the buffer at completion and it has some characters remaining in it. I'm not sure why this might lead to it hanging up and not giving me an exit code with my R script but that's my best guess as to what is going on. 

I am attaching some files to help you reproduce, the Console app code I used to test as well as the stdOut and stdErr files I used. For those I just replaced all alphanumeric characters with random characters so that any sensitive debugging info is not in there (note: i tested with these random files too, same result). Hopefully this helps.


[Program.cs.txt](https://github.com/Tyrrrz/CliWrap/files/4634389/Program.cs.txt)
[stderr-rnd.txt](https://github.com/Tyrrrz/CliWrap/files/4634390/stderr-rnd.txt)
[stdout-rnd.txt](https://github.com/Tyrrrz/CliWrap/files/4634391/stdout-rnd.txt)

**Comment by Tyrrrz** [comment]
Thanks a lot. I will take a look and try to reproduce it locally.

Unfortunate that you weren't able to get it to hang as well, that means the issue is probably somewhere else then :/

**Comment by Tyrrrz** [comment]
So I tried to reproduce this, using your `Program.cs` and `stdout-rnd.txt`/`stderr-rnd.txt` files, and also my snippet with the piping setup. It works as expected and doesn't hang.

The produced output is also the exact same size as the `stdxxx-rnd.txt` files, except extra 2 bytes due to `Console.WriteLine`.

So I couldn't get it to hang or get the file size to be multiple of 4096 either.

**Comment by Tyrrrz** [comment]
It does seem though that the buffer is not flushed at the end of command execution. In my case the console app just closed so it was flushed automatically for me. Still wouldn't explain the hangs though.

**Comment by Tyrrrz** [comment]
Nevermind, the streams are flushed when they are disposed by the consumer, not CliWrap. So in this case I just had a `using` that spans the entire method. Seems like there aren't any problem with this either.

**Comment by scott-mac** [comment]
Ahh I see my error now, I was looking at the file 'size on disk' property which is allocated by blocks so it makes sense that it was 4096, ok sorry about that, I sent us down a rabbit hole there on that one :(.

All I can think then is that it's something about the nature of the RScript.exe executable that I'm calling via CliWrap that leads to the hang when it doesn't read the full output. You say it's not getting flushed at the end of execution though, is that something you can fix easily? I'm just wondering if that is somehow related to the issue I'm getting...but even if it is not, I can work around it if I get the full stdout read back to me because my last line in the R script code is basically

print("COMPLETE")

so as long as I can read that then I know it is done and I can do my cleanup code

**Comment by Tyrrrz** [comment]
I really can't think of anything that could cause RScript.exe to hang. I would have to debug on the real thing to get some clues.

As for flushing, like I said in another comment, it happens on `Dispose()`/`DisposeAsync()`. So you actually control the flushing yourself, since you provide the stream itself. I believe it may also flush in between when the buffer reaches a certain size. Basically, the snippet of code I've shared earlier should work, the streams are disposed at the end of the method there.

**Comment by scott-mac** [comment]
OK but remember in my initial scenario I wasn't ever writing to any files, I was just reading into StringBuilders, so what would I need to do to ensure that the remaining characters held in the buffer are getting flushed?

**Comment by Tyrrrz** [comment]
That should just be flushed automatically as there's no buffering:

https://github.com/Tyrrrz/CliWrap/blob/61875fab524bb349bc5237b2bc5ce7931b3be69e/CliWrap/PipeTarget.cs#L109-L132

**Comment by scott-mac** [comment]
All i can think might be going on here is that the R script is exceeding the available memory on the server (these calculations can be intensive) and its somehow causing the process to not exit cleanly. I know when I run it locally it pretty pegs my machine near 100% for several minutes. Can you see anything in your code that might account for the behavior I'm seeing with a process running at full memory capacity? Any way I could test this theory? Does CliWrap have any kind of internal debugging that I can turn on and maybe see what's going on? Thanks for your help on this

**Comment by Tyrrrz** [comment]
100% CPU usage is completely fine. If it runs out of memory, it should crash, not freeze, otherwise it should be fine too.

There isn't any kind of additional logging. You could clone the sources and debug directly though.

**Comment by scott-mac** [comment]
OK, here's the thing that doesn't add up though... I can run the script from my own command line and regardless of the spiking memory usage or verbosity etc, it always completes and I get all the stdout and stderr written to my console, it never hangs. 

I did some research on people who had similar issues and came across the following, I think this might be what is happening. If you look at the selected answer it explains it pretty well, if I implement that it works seamlessly, i get an exit code and all the stdout and stderr messages are captured. Could this be what is happening?

https://stackoverflow.com/questions/60208678/process-sometimes-hangs-while-waiting-for-exit

**Comment by Tyrrrz** [comment]
CliWrap doesn't use the approaches outlined in that post (`OutputDataReceived`/`ErrorDataReceived`, etc) because it works with binary data.

The streams themselves are handled in parallel: https://github.com/Tyrrrz/CliWrap/blob/61875fab524bb349bc5237b2bc5ce7931b3be69e/CliWrap/Command.cs#L267-L272

There are also tests that cover this behavior:

https://github.com/Tyrrrz/CliWrap/blob/61875fab524bb349bc5237b2bc5ce7931b3be69e/CliWrap.Tests/GeneralSpecs.cs#L46-L56

https://github.com/Tyrrrz/CliWrap/blob/61875fab524bb349bc5237b2bc5ce7931b3be69e/CliWrap.Tests/PipingSpecs.cs#L391-L417

https://github.com/Tyrrrz/CliWrap/blob/61875fab524bb349bc5237b2bc5ce7931b3be69e/CliWrap.Tests/BufferedSpecs.cs#L77-L93

**Comment by scott-mac** [comment]
Ok well I guess close the issue, I'll have to go with a different solution for what we need. Thanks

**Comment by Tyrrrz** [comment]
What you're describing clearly sounds like a bug but I have no way to identify what's wrong without being able to debug it directly. As far as the code goes, everything _should_ work and as you can see there are also tests that cover specific deadlock scenarios. If I don't have access to an environment where the issue is reproduced consistently, there's not much I can do except to guess.
