### ISSUE TITLE
Option to trigger `DelegatePipeTarget` every time the process pushes new data, instead of only on line breaks

### ISSUE THREAD

**Issue by klacol** [Tyrrrz/CliWrap#66]
I use 7Zip with the -bsp1 option. This writes the progress as percentages, e.g.

1%
2%
3% 

and so on.

But 7Zip always updates the line and writes no new line, so I cannot catch the percentage in CliWrap.

Is there any option to catch also stout lines that are permantly updates by the process?

**Comment by Tyrrrz** [comment]
As far as stdout is concerned, the lines are written as "1%2%3%". 7Zip just changes the cursor position so that the text in the console is overwritten, but it doesn't affect the actual data streams themselves.

You can make your own `PipeTarget` that looks for some other specific characters or just handles the entire stdout. For example, here's how I do something similar for FFmpeg, I'm just building a buffer dynamically and looking for progress in the whole string.

https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/de02be0fa39d8655ee76c2ff3ce82795240e41a9/YoutubeExplode.Converter/Internal/FFmpeg.cs#L69-L120

It's not supper efficient of course, but I haven't been able to come up with a better approach, so suggestions are welcome.

**Comment by Tyrrrz** [comment]
Worth noting, it seems that `Process`'s own `BeginOutputReadLine`/`BeginErrorReadLine` actually seem to trigger on data even if it doesn't contain a line break, as long as the process flushes the streams after writing the data.

I think the approach they use is the following:
- `stream.ReadAsync(...)`
- Decode the content as text
- Split it by line breaks
- Yield all segments

If there are no line breaks, this results in yielding the entire content. Our approach is different in that we don't yield until we encounter a line break or EOF.

When it comes to API, I think we can get away by defining an enum `DataYieldTrigger` (name up for discussion) with values `DataYieldTrigger.LineBreak` (current) and `DataYieldTrigger.Flush` (proposed behavior). We'll use it as a parameter in `PipeTarget.ToDelegate(...)`, `Command.ListenAsync(...)`, and `Command.Observe(...)`. The underlying `PipeTarget` implementation for the new mode will probably be separate from the current `DelegatePipeTarget` and `AsyncDelegatePipeTarget` to not overcomplicate the logic in `StreamReader.ReadAllLinesAsync(...)` extension, but maybe not -- we'll see what makes the most sense.

**Comment by Tyrrrz** [comment]
After researching this a bit, it seems that there is no way to reliably trigger a delegate every time a process flushes data. Even though `ReadAsync(...)` appears to return as soon as it has any data to yield (which seems to coincide with the process flushing that data), this also works only if the `StreamReader`'s buffer is bigger than that of the process's stdout/stderr buffer (which can be of arbitrary size). So I don't think we can add anything general purpose on CliWrap's side to solve this.

Instead, if you need to handle flushed data even if doesn't contain line breaks, you can create your own `PipeTarget`:

```csharp
class FFmpegProgressRouter : PipeTarget
{
    public override async Task CopyFromAsync(Stream source, CancellationToken cancellationToken = default)
    {
		// Buffer must be bigger than the process's stdout buffer
		const int bufferSize = 1024;

        using var reader = new StreamReader(source, Console.OutputEncoding, false, bufferSize, true);
        var buffer = new char[bufferSize];

        int charsRead;
        while ((charsRead = await reader.ReadAsync(buffer, 0, buffer.Length)) > 0)
        {
            cancellationToken.ThrowIfCancellationRequested();
            
			var data = new string(buffer, 0, charsRead);

			// Do something with data here
        }
    }
}
```
