### ISSUE TITLE
How to handle apps that do not give an exit code?

### ISSUE THREAD

**Issue by netleader** [Tyrrrz/CliWrap#67]
First, very nice library!
Now to my problem, I use it to merge MKV files with mkvmerge (v46) but i have the problem that mkvmerge finishes but gives appenrently no exit code so my app hangs and i need to restart it.

How do you handle this case?

**Comment by Tyrrrz** [comment]
Hi.
I don't think it's possible for an app to not return exit code. Maybe it hangs for another reason? Does it merge the files successfully or is it stuck too?

**Comment by netleader** [comment]
The muxing it self always goes through:

`Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 1 minute 44 seconds.`

I'm a bit lost I tried to throw a cts once i get this response but that didn't work.

**Comment by Tyrrrz** [comment]
That's weird. Could you provide a minimal repro? Code + where to download mkvmerge that you're using + MKV files that you're merging (if they're too big, maybe this problem is reproducible with smaller files too?).

**Comment by netleader** [comment]
I cant believe it... while putting toghether everything I found that my arguments have a very small bug :( Sorry for anoying you! It works now.

**Comment by Tyrrrz** [comment]
Don't worry. What was the error after all?

**Comment by netleader** [comment]
A track with the ID 0 was requested but not found in the file. The corresponding option will be ignored. Ive added the subtitles with the wring track IDs....

**Comment by Tyrrrz** [comment]
Hm. Weird that it would cause it to hang.
