### ISSUE TITLE
How to run an embedded resource executable?

### ISSUE THREAD

**Issue by hulaomr** [Tyrrrz/CliWrap#70]
Hello, 
Sorry for beginner question. 
I would like to use this library to run an embedded resource executable. I cannot find any documentation or reference.
The idea is to hide the application from the user. 
Thanks!

**Comment by Tyrrrz** [comment]
Hello.
This is not possible to do directly, to my knowledge.
Your best plan would be to extract the resource to a temporary directory, run it, and then delete it.

**Comment by hulaomr** [comment]
Thanks for your feedback Alexey. I followed your suggestion.
About the details, as information for others in the same situation, I created a temporal file following [this](https://stackoverflow.com/a/9719279/4622162) approach and delete it automatically follow this [other](https://stackoverflow.com/a/400391/4622162).

**Comment by Tyrrrz** [comment]
Glad it helped!
