### ISSUE TITLE
How to pipe interactive input from parent stdin into the target process?

### ISSUE THREAD

**Issue by DaRosenberg** [Tyrrrz/CliWrap#74]
Hello,

In our CLI program, we are invoking `git mergetool` on the user's behalf, and we want to pipe input and output unaltered between the parent process, and the target process (git) for the duration of the target command execution.

We have tried various variations of the following:

```cs
await using var stdIn = Console.OpenStandardInput();
await using var stdOut = Console.OpenStandardOutput();
await using var stdErr = Console.OpenStandardError();

var cmd =
	Cli.Wrap("git")
		.WithWorkingDirectory(@"C:\SomeRepository")
		.WithArguments("mergetool")
		.WithStandardInputPipe(PipeSource.FromStream(stdIn))
		.WithStandardOutputPipe(PipeTarget.ToStream(stdOut))
		.WithStandardErrorPipe(PipeTarget.ToStream(stdErr));

var result = await cmd.ExecuteAsync();
```

The piping of `stdout` and `stderr` seem to work as expected. However, input from `stdin` does not seem to get passed to the target process, because it does absolutely nothing in response to the input while prompting.

To illustrate:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/3889090/85453877-9eaec180-b59c-11ea-8cee-8956c0b80a59.png">

What are we doing wrong? Any advice would be greatly appreciated.

**Comment by Tyrrrz** [comment]
Does it work if you insert the end-of-input character (`^z` aka `ctrl+z`)?

**Comment by DaRosenberg** [comment]
It definitely changes something, but I can't make sense of exactly what's happening.  It's like, nothing happens until I send `^Z` + `Enter` (just `^Z` does nothing) and at that point it looks a bit like `git.exe` processes all the input.

Looks like this:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/3889090/85469927-99f30900-b5ae-11ea-8aab-42b228d731a1.png">

First the prompt shows, then I type `a` + `Enter` + `n` + `Enter`, then `^Z` + `Enter` and then `git.exe` exits with exit code 1.

Does it tell you anything?

**Comment by paynecrl97** [comment]
I created a simple repo to help with reproduction: https://github.com/paynecrl97/FileMergeConflicts

1. Clone the repo, and checkout the `master` branch.
1. Use Git to merge the `mergeMeIntoMaster` branch into `master`. You'll encounter conflicts, this is expected.
1. Run the program at the top of this thread (you'll need to change the working directory to the directory that you cloned the repo to)

**Comment by Tyrrrz** [comment]
Thanks for the repro, I'll check it when I have a bit more time.

**Comment by Tyrrrz** [comment]
I reproduced this, looks like there are two issues:
1. When copying stdin from a stream, the data is not flushed at earliest opportunity.
2. When the underlying command finishes before stdin is fully read (in this case `Console.OpenStandardInput()` is not closed during command's lifetime and is technically infinite) then the execution deadlocks

I'm working on a fix now.

**Comment by Tyrrrz** [comment]
Released a fix.

**Comment by Tyrrrz** [comment]
@DaRosenberg curious if you've tried the new version already and it works as you expect.

**Comment by DaRosenberg** [comment]
@Tyrrrz yes, tested this with 3.1.0 in the repro project I set up, and it works perfectly now. Thanks for the speedy fix! 👍
