### ISSUE TITLE
PipeTarget.ToDelegate splits output into smaller chunks when merged with another pipe

### ISSUE THREAD

**Issue by paynecrl97** [Tyrrrz/CliWrap#75]
Create a simple console app that prints one, long, continuous string:

```
	class Program
	{
		static void Main(string[] args)
		{
			Console.Out.Write(new String('x', 100000));
		}
	}
```

Now, create two unit tests:
```
[TestFixture]
public class Tests
{

	[Test]
	public async Task Test1()
	{
		var outputBuilder = new StringBuilder();

		await Cli.Wrap(@"<pathToTestApp>")
			.WithStandardOutputPipe(PipeTarget.ToStringBuilder(outputBuilder))
			.ExecuteAsync();

		var output = outputBuilder.ToString();

		Assert.False(output.Contains(Environment.NewLine));
	}

	[Test]
	public async Task Test2()
	{
		var outputBuilder = new StringBuilder();

		await Cli.Wrap(@"<pathToTestApp>")
			.WithStandardOutputPipe(PipeTarget.ToDelegate(line => {outputBuilder.AppendLine(line); }))
			.ExecuteAsync();

		var output = outputBuilder.ToString();

		Assert.False(output.Contains(Environment.NewLine));
	}
}
```

The first will pass, as expected. The second will fail.

It appears that the delegate `PipeTarget` is splitting a single, long line in to multiple lines. We're using the delegate target because we want to do some other things to the output than just writing to the StringBuilder (i.e. logging).

**Comment by Tyrrrz** [comment]
The second test fails because of `outputBuilder.AppendLine(line)`. Replace with `Append` and it will work.

**Comment by paynecrl97** [comment]
Ah it's a flawed test, you're right.

I had tried to reduce the issue down to the simplest form for reproduction. Here's the original problem though:

We were running `git status -z -u` on a repo with a large number of changes. When using `PipeTarget.ToDelegate`, the output from Git was incorrectly interspersed with new line characters, but this was not the case when using `PipeTarget.ToStringBuilder`.

I'll see if I can create a valid reproduction test

**Comment by Tyrrrz** [comment]
I tried to reproduce it with a very long line of characters and it didn't happen. A working repro would be really nice.

**Comment by paynecrl97** [comment]
OK, think I've got it now:

Console app:

```
		static void Main(string[] args)
		{
			Console.Out.WriteLine(new String('x', 10000000));
			Console.Out.WriteLine(new String('y', 100000));
			Console.Out.WriteLine(new String('z', 100000));
		}
```

Test:
```
[Test]
public async Task Test1()
{
	var cliPath = @"C:\Users\Chris\source\repos\CliWrapV3\CliWrapV3\bin\Debug\netcoreapp3.1\CliWrapV3.exe";

	var stringBuilderOutput = new StringBuilder();
	var delegateOutput = new StringBuilder();

	var stringBuilderResult = await Cli.Wrap(cliPath)
		.WithStandardOutputPipe(PipeTarget.ToStringBuilder(stringBuilderOutput))
		.ExecuteBufferedAsync(Encoding.UTF8);

	var delegateResult = await Cli.Wrap(cliPath)
		.WithStandardOutputPipe(PipeTarget.ToDelegate(line => { delegateOutput.AppendLine(line); }))
		.ExecuteBufferedAsync(Encoding.UTF8);

	var stringBuilderResultNewLines = stringBuilderResult.StandardOutput.Split(Environment.NewLine);
	var delegateResultNewLines = delegateResult.StandardOutput.Split(Environment.NewLine);

	var stringBuilderNewLines = stringBuilderOutput.ToString().Split(Environment.NewLine);
	var delegateNewLines = delegateOutput.ToString().Split(Environment.NewLine);

	Assert.Multiple(() =>
	{
		Assert.AreEqual(stringBuilderResultNewLines.Length, delegateResultNewLines.Length, "Results not equal");
		Assert.AreEqual(stringBuilderNewLines.Length, delegateNewLines.Length, "Pipes not equal");
	});
}
```

Fails as: 

```
  Message: 
      Pipes not equal
      Expected: 4
      But was:  3287
```

My suspicion is that when you use `ExecuteBufferedAsync`, the `PipeTarget` delegate is not batched up in to lines, i.e. the input to that delegate is not a complete line of output. 

I don't know if that is expected or not, but it seems counter intuitive to change the behaviour of that delegate based on how you call execute.

It also complicates things such as logging or tracing the output as it comes in.

**Comment by Tyrrrz** [comment]
Released a fix.

**Comment by Tyrrrz** [comment]
@paynecrl97 have you tried the new version already? Does it work as you intended?

**Comment by paynecrl97** [comment]
Yes, we were able to update and can confirm it’s working as expected. Thank you
