### ISSUE TITLE
Is it possile to get stdout and stderr for process not awaiting?

### ISSUE THREAD

**Issue by przemo1983** [Tyrrrz/CliWrap#76]
I have a trouble with getting standard output and standard error data from process when that process is not awaited.
When I add await keyword to the ExecuteAsync function the code is working correctly.
I know that approach of fire&forget is to not care about the process but I have to check the output from that process from time to time, while another process is awaited all the time.

Is it possible using current implementation?

I tried following code but with no success:
```
await using var stdOut = Console.OpenStandardOutput();
await using var stdErr = Console.OpenStandardError();

var cmd = Cli.Wrap("foo") | (stdOut, stdErr);
cmd.ExecuteAsync();
```
and
```
var cmd = Cli.Wrap("foo") | Debug.WriteLine;
cmd.ExecuteAsync();
```

**Comment by Tyrrrz** [comment]
The examples you showed should work, although something still has to await the execution of the command, albeit on another thread.

If you're interested in textual data then the event stream model might be more applicable to you.
