### ISSUE TITLE
UNC path as WorkingDirectory

### ISSUE THREAD

**Issue by vbugarsk** [Tyrrrz/CliWrap#78]
Is there some way to set `WorkingDirectory` to UNC path ?

**Comment by Tyrrrz** [comment]
It's passed directly to `ProcessStartInfo.WorkingDirectory` so if that doesn't support it then no.

**Comment by vbugarsk** [comment]
You are right, `ProcessStartInfo.WorkingDirectory` doesn't support UNC path. Just as a reference, it seems this snippet works fine even if `workingDirectory` is UNC path. Command `pushd` maps UNC path temporary (for this process only):

```
private async Task<int> RunProcessAsync(string command, string workingDirectory)
{
    var fullCmd = new StringBuilder();
    fullCmd.AppendLine($"pushd \"{workingDirectory}\"");
    fullCmd.AppendLine(command);

    var cmd = Cli.Wrap("cmd.exe")
        .WithStandardInputPipe(PipeSource.FromString(fullCmd.ToString()))
        .WithValidation(CommandResultValidation.None);

    var result = await cmd.ExecuteAsync();

    return result.ExitCode;
}
```

**Comment by Tyrrrz** [comment]
Out of curiosity, why are you trying to set working directory using UNC path?

**Comment by vbugarsk** [comment]
I am developing some system for my company, for remote monitoring and remote installations for our Windows clients (about 200 users). Each client machine will run Windows service, and will be able to run process on administrators demand. All our installations are on remote file shares (UNC path). Surely I can do it without mapping UNC path but then my commands (`ProcessStartInfo.FileName` and arguments `ProcessStartInfo.Arguments` will have to include it which is sometimes quite long. I saw that both SCCM and Windows Deployment Toolkit (WDT) works on that way that you set UNC working directory and then your commands/args are simpler. Behind the scene both SCCM and WDT maps UNC path to drives. That is exactly what I wanted. Hope this clarifies a bit :)

**Comment by Tyrrrz** [comment]
Thanks!
