### ISSUE TITLE
Kill all executing child processes when the host process exits

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliWrap#8]
It would be nice to automatically kill all children if the parent is dying. Life as an orphan isn't a life worth living.

Relevant:
https://stackoverflow.com/a/2555354/2205454

**Comment by Tyrrrz** [comment]
Suggested approach: track all running processes in a list, remove from the list when the process is dead. When the ApplicationExit event fires, kill all remaining processes.

**Comment by Tyrrrz** [comment]
Added `help wanted` because it's a good first-time issue to fix while i'm away from keyboard :p

**Comment by gmkado** [comment]
Sorry to resurrect this but does the fix from #11 still apply?  I'm finding that processes started with `Cli.Wrap(...).ExecuteAsync` outlive the host process.

It happens on Windows when I kill the process forcefully (via rider stop button) so I'm guessing something isn't getting disposed properly.  Is this just a limitation of the OS?

**Comment by Tyrrrz** [comment]
@gmkado no, this feature has been reworked since then.

It's now recommended, in a general case, to use a "kill switch" type cancellation token that gets reused across all commands and triggers on application shutdown: https://github.com/Tyrrrz/CliWrap#timeout-and-cancellation

This is equivalent to what #11 did, but gives more control to the developer.

This is not a fool-proof solution though, because it won't work for a process that was terminated forcefully. In such a case, you would typically use native OS constructs, such as process groups, but CliWrap does not provide any APIs for that.
