### ISSUE TITLE
NullReferenceException when running against .net5 on Windows

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliWrap#97]
Updating the CI infra to .NET 5 revealed a potential bug:

https://github.com/Tyrrrz/CliWrap/runs/1382321148?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1935960/98740865-66c1e280-23b4-11eb-9749-567e85870fe0.png)

Looks like the compiler generated code is throwing? Could be a Fody issue? Can't replicate locally so probably will need to investigate with `Console.WriteLine()` on CI.

**Comment by Tyrrrz** [comment]
Update: replicated locally when running with `--configuration Release`:

![image](https://user-images.githubusercontent.com/1935960/98823702-180b5b80-243b-11eb-8db0-9ca848ea8ef7.png)

Smells like a Fody issue, but curious that it only happens on this two tests consistently.

**Comment by warappa** [comment]
@Tyrrrz 
Happened to me while trying to use `YoutubeExplode.Converter` in release configuration (debug configuration works).

### Workaround
Removing `<ConfigureAwait ContinueOnCapturedContext="false" />` from `FodyWeavers.xml` prevents this error in release configuration.

Definitely a Fody problem.

**Comment by Tyrrrz** [comment]
@warappa does it work if you manually install/update CliWrap to latest?

**Comment by warappa** [comment]
Updated everything I can, didn't help.

Wild guess: ConfigureAwait.Fody cannot can not be applied multiple times (first in CliWrap and then in YouTubeExplode.Converter using CliWrap).

**Comment by Tyrrrz** [comment]
@warappa I pushed YoutubeExplode.Converter 2.0.2 which should fix it. By the looks of it, Fody doesn't properly handle CliWrap's own awaitable (`CommandTask`), which seems like it only started happening since .net5.0. For now, you can't use Fody.ConfigureAwait and CliWrap together it seems. I can't create an issue on Fody's repo since I'm not a paid subscriber, so for now I'll just remove Fody from all projects that reference ClIWrap and think how to proceed later.
