### ISSUE TITLE
Missing WithTargetFilePath() method

### ISSUE THREAD

**Issue by 8** [Tyrrrz/CliWrap#98]
Hi,

I was looking for a `WithTargetFilePath()` method, but I didn't find any.

e.g. You have a command `Command` and now you want to wrap in another shell, e.g. run it using `wsl`.
On the shell, I just need to prepend `wsl` before the command
The same goes for different versions of executables that differ only by name.

Did I miss anything / Is there another some design reason why this is not supported?

Thank you!

Take care,
Martin

**Comment by Tyrrrz** [comment]
Hi.

The `With...` methods were added as a more convenient way to configure optional parameters. The target file path is the only parameter which is not optional, so there is no `With...` method for it. That's pretty much the only reason.

I could see the benefit of adding it for the use case you explain, but wouldn't it be easier to do something like this?

```csharp
public Command GetMyCommand(string shell, string command) =>
    Cli.Wrap(shell).WithArguments(new[]{"-c", command});
```
