### ISSUE TITLE
Carriage returns (\r) are not handled correctly

### ISSUE THREAD

**Issue by koryphaee** [Tyrrrz/CliWrap#99]
I recently started using this library and have been very happy with so far.
The way it wraps the Process class in an async and fluid fashion is just fantastic. 
However, I have found one small bug:

Some programs use carriage returns at the beginning of their output to reset the cursor to the start of the line.
This is useful for interactive programs that display some sort of progress because that way they don't spam your terminal.

One example is [youtube-dl](https://github.com/ytdl-org/youtube-dl). The output of `youtube-dl https://www.youtube.com/watch?v=dQw4w9WgXcQ`
could look like this (with \n and \r visible), which continuously replaced the second line with a new one.
```
[youtube] dQw4w9WgXcQ: Downloading webpage\n
\r[download]  10.0% of 107.66MiB at 1MiB/s ETA 01:00
\r[download]  20.0% of 107.66MiB at 1MiB/s ETA 00:50
...
\r[download]  100.0% of 107.66MiB at 1MiB/s ETA 00:00\n
```

CliWrap does not handle this correctly and only returns two lines:
```
[youtube] dQw4w9WgXcQ: Downloading webpage
[download]  10.0% of 107.66MiB at 1MiB/s ETA 01:00[download]  20.0% of 107.66MiB at 1MiB/s ETA 00:50[download]  30.0% of 107.66MiB at 1MiB/s ETA 00:40
```
Another resulting issue is that this line is only written to the pipe when the last real line is printed. This makes it impossible to parse the download progress while the download is still running.

I will try to look into the code and see if I can come up with a fix by myself.
If that is the case I will create a pull request.
I hope that I can help to make this awesome library a tiny bit better.

**Comment by Tyrrrz** [comment]
Hi!

This might be related to #66. I didn't know FFmpeg actually writes `\r`, I thought it just moved the cursor position.

Currently, the line breaks are handled by explicitly looking for `\n`. Example:

https://github.com/Tyrrrz/CliWrap/blob/6c4a6688f55224fbce0bb4dfff0da91fd2e04345/CliWrap/PipeTarget.cs#L152-L174

Which uses:

https://github.com/Tyrrrz/CliWrap/blob/6c4a6688f55224fbce0bb4dfff0da91fd2e04345/CliWrap/Internal/Extensions/StreamExtensions.cs#L27-L54

As a simple solution, we could extend it so it triggers on lone `\r` as well. A more extended solution would be to let the user control the separations process themselves somehow, but I'm not sure how commonly would you need something other than `\n` or `\n` anyway.

**Comment by koryphaee** [comment]
Thank you for the quick response and the lead on how to implement it.

The pull request is here: https://github.com/Tyrrrz/CliWrap/pull/100.
I managed to build a solution that handles all existing cases plus this new one without requiring manual user configuration.

Regarding your idea for custom separation:
Since this is just a helper method for the DelegatePipeTarget I don't think it should be overly complex.
When a user really needs something custom they can easily write their own PipeTarget.
I even considered closing this issue and writing my own PipeTarget because my use-case is already pretty niche.
I guess this would fix https://github.com/Tyrrrz/CliWrap/issues/66 also, so there is some demand I guess.

**Comment by nadjibus** [comment]
> One example is [youtube-dl](https://github.com/ytdl-org/youtube-dl). The output of `youtube-dl https://www.youtube.com/watch?v=dQw4w9WgXcQ`

Why am I not surprised...
![image](https://user-images.githubusercontent.com/3637280/102259808-e12fd600-3f0f-11eb-9a1f-551ebed3ccfa.png)

Anyway great job thank you for the PR, was having the same problem with \r
